# CMake generated Testfile for 
# Source directory: /Users/elijahbonds/Developer/FEL-nexus-build
# Build directory: /Users/elijahbonds/Developer/FEL-nexus-build/build-gate
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[nexus_protocol_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_protocol_test")
set_tests_properties([=[nexus_protocol_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;281;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_agent_cli_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_agent_cli_test")
set_tests_properties([=[nexus_agent_cli_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;286;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_gameplay_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_gameplay_test")
set_tests_properties([=[nexus_gameplay_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;295;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_scan_envelope_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_scan_envelope_test")
set_tests_properties([=[nexus_scan_envelope_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;303;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_generative_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_generative_test")
set_tests_properties([=[nexus_generative_test]=] PROPERTIES  WORKING_DIRECTORY "/Users/elijahbonds/Developer/FEL-nexus-build" _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;307;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_physics_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_physics_test")
set_tests_properties([=[nexus_physics_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;312;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_physics_advanced_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_physics_advanced_test")
set_tests_properties([=[nexus_physics_advanced_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;316;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_job_system_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_job_system_test")
set_tests_properties([=[nexus_job_system_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;320;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_cartridge_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_cartridge_test")
set_tests_properties([=[nexus_cartridge_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;324;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_scale_policy_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_scale_policy_test")
set_tests_properties([=[nexus_scale_policy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;328;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_cell_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_cell_test")
set_tests_properties([=[nexus_cell_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;332;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_youtube_learner_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_youtube_learner_test")
set_tests_properties([=[nexus_youtube_learner_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;336;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_realtime_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_realtime_test")
set_tests_properties([=[nexus_realtime_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;340;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_renderer_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_renderer_test")
set_tests_properties([=[nexus_renderer_test]=] PROPERTIES  WORKING_DIRECTORY "/Users/elijahbonds/Developer/FEL-nexus-build" _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;345;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
add_test([=[nexus_console_tier_test]=] "/Users/elijahbonds/Developer/FEL-nexus-build/build-gate/nexus_console_tier_test")
set_tests_properties([=[nexus_console_tier_test]=] PROPERTIES  WORKING_DIRECTORY "/Users/elijahbonds/Developer/FEL-nexus-build" _BACKTRACE_TRIPLES "/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;350;add_test;/Users/elijahbonds/Developer/FEL-nexus-build/CMakeLists.txt;0;")
