# CMake generated Testfile for 
# Source directory: /home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab
# Build directory: /home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[nexus_protocol_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_protocol_test")
set_tests_properties([=[nexus_protocol_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;295;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_agent_cli_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_agent_cli_test")
set_tests_properties([=[nexus_agent_cli_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;300;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_cell_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_cell_test")
set_tests_properties([=[nexus_cell_test]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab" _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;305;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_gameplay_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_gameplay_test")
set_tests_properties([=[nexus_gameplay_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;314;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_scan_envelope_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_scan_envelope_test")
set_tests_properties([=[nexus_scan_envelope_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;322;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_dunk_contest_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_dunk_contest_test")
set_tests_properties([=[nexus_dunk_contest_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;330;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_golf3d_karate_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_golf3d_karate_test")
set_tests_properties([=[nexus_golf3d_karate_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;338;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_story_mode_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_story_mode_test")
set_tests_properties([=[nexus_story_mode_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;346;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_generative_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_generative_test")
set_tests_properties([=[nexus_generative_test]=] PROPERTIES  WORKING_DIRECTORY "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab" _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;350;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_physics_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_physics_test")
set_tests_properties([=[nexus_physics_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;355;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_physics_advanced_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_physics_advanced_test")
set_tests_properties([=[nexus_physics_advanced_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;359;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_job_system_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_job_system_test")
set_tests_properties([=[nexus_job_system_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;363;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_cartridge_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_cartridge_test")
set_tests_properties([=[nexus_cartridge_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;367;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_scale_policy_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_scale_policy_test")
set_tests_properties([=[nexus_scale_policy_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;371;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_realtime_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_realtime_test")
set_tests_properties([=[nexus_realtime_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;375;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
add_test([=[nexus_net_test]=] "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/build-gate/nexus_net_test")
set_tests_properties([=[nexus_net_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;379;add_test;/home/runner/work/Final-Evolution-Lab/Final-Evolution-Lab/CMakeLists.txt;0;")
subdirs("_deps/nlohmann_json-build")
