/* AUTO-GENERATED by scripts/generate-design-tokens.js from infra/design_tokens.json (v1.0.0).
 * Do not edit by hand — edit the JSON and run `npm run tokens`.
 *
 * Raw values for JS consumers (canvas, WebGL, web audio, rAF animations).
 * For styling, prefer the CSS variables in tokens.css: var(--fel-color-accent-primary) etc.
 */
export const color = {
  "ink": "#050505",
  "surface-1": "#0B0B0E",
  "surface-2": "#121218",
  "surface-3": "#1A1A22",
  "text-primary": "#FFFFFF",
  "text-secondary": "rgba(255, 255, 255, 0.72)",
  "text-muted": "rgba(255, 255, 255, 0.48)",
  "text-inverse": "#050505",
  "accent-primary": "#00D4FF",
  "accent-primary-hover": "#33DDFF",
  "accent-primary-active": "#00A8CC",
  "accent-primary-muted": "rgba(0, 212, 255, 0.14)",
  "accent-secondary": "#9933FF",
  "accent-secondary-hover": "#AD5CFF",
  "accent-secondary-muted": "rgba(153, 51, 255, 0.14)",
  "success": "#38D39F",
  "success-muted": "rgba(56, 211, 159, 0.14)",
  "danger": "#FF5C5C",
  "danger-muted": "rgba(255, 92, 92, 0.14)",
  "warning": "#FFB86C",
  "warning-muted": "rgba(255, 184, 108, 0.14)",
  "border": "rgba(255, 255, 255, 0.08)",
  "border-strong": "rgba(255, 255, 255, 0.16)",
  "border-focus": "#00D4FF",
  "backdrop": "rgba(5, 5, 5, 0.72)"
};

export const font = {
  "display": "'Barlow Condensed', 'Avenir Next Condensed', 'Arial Narrow', system-ui, sans-serif",
  "ui": "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  "mono": "ui-monospace, 'SF Mono', Menlo, Consolas, monospace"
};

export const text = {
  "sm": {
    "size": "14px",
    "line": "20px",
    "weight": "400",
    "tracking": "0"
  },
  "base": {
    "size": "16px",
    "line": "24px",
    "weight": "400",
    "tracking": "0"
  },
  "lg": {
    "size": "20px",
    "line": "28px",
    "weight": "600",
    "tracking": "0"
  },
  "xl": {
    "size": "28px",
    "line": "34px",
    "weight": "700",
    "tracking": "-0.01em"
  },
  "2xl": {
    "size": "36px",
    "line": "42px",
    "weight": "700",
    "tracking": "-0.015em"
  },
  "3xl": {
    "size": "56px",
    "line": "60px",
    "weight": "800",
    "tracking": "-0.02em"
  }
};

export const space = {
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "5": "24px",
  "6": "32px",
  "7": "48px",
  "8": "64px"
};

export const radius = {
  "sm": "6px",
  "md": "12px",
  "lg": "16px",
  "pill": "999px",
  "round": "50%"
};

export const elevation = {
  "1": "0 1px 2px rgba(0, 0, 0, 0.4), 0 2px 8px rgba(0, 0, 0, 0.35)",
  "2": "0 2px 4px rgba(0, 0, 0, 0.4), 0 8px 24px rgba(0, 0, 0, 0.45)",
  "3": "0 4px 8px rgba(0, 0, 0, 0.45), 0 16px 48px rgba(0, 0, 0, 0.55)",
  "glow-cyan": "0 0 0 1px rgba(0, 212, 255, 0.25), 0 0 20px rgba(0, 212, 255, 0.3)",
  "glow-purple": "0 0 0 1px rgba(153, 51, 255, 0.25), 0 0 20px rgba(153, 51, 255, 0.3)"
};

/** Durations/easings as strings ("120ms"). Use motionMs for numeric values. */
export const motion = {
  "fast": "120ms",
  "normal": "240ms",
  "slow": "480ms",
  "stagger": "40ms",
  "ease": "cubic-bezier(0.2, 0.9, 0.3, 1)",
  "ease-out": "cubic-bezier(0.16, 1, 0.3, 1)",
  "ease-in": "cubic-bezier(0.6, 0, 0.8, 0.4)"
};

/** Motion durations in numbers (ms) for JS-driven animation. */
export const motionMs = {
  fast: 120,
  normal: 240,
  slow: 480,
  stagger: 40,
};

/** Audio mix levels in dBFS relative to master (not CSS-facing). */
export const audio = {
  "ui-sfx-db": -6,
  "ui-sfx-prominent-db": -3,
  "music-bed-db": -18,
  "music-bed-min-db": -20,
  "music-bed-max-db": -15,
  "ducking-db": -8
};

/** cssVar("color", "accent-primary") -> "var(--fel-color-accent-primary)" */
export const cssVar = (group, name, sub) =>
  `var(--fel-${group}-${name}${sub ? `-${sub}` : ""})`;

/** True when the user prefers reduced motion (guard rAF/JS-driven animation with this). */
export const prefersReducedMotion = () =>
  typeof window !== "undefined" &&
  window.matchMedia &&
  window.matchMedia("(prefers-reduced-motion: reduce)").matches;

const felTokens = { color, font, text, space, radius, elevation, motion, motionMs, audio, cssVar, prefersReducedMotion };
export default felTokens;
