// WhoSceneItMode — identify the venue from the scene. 8 questions, 14s each.
//
// The prompt is RENDERED: each question names a venue id and the mode rebuilds
// that venue behind the answers. No stills, no posters, no likenesses — every
// scene is generated by this codebase, which is what makes a scene-recall game
// shippable here at all.
import { createQuizMode } from './QuizMode';
import { WHO_SCENE_IT } from '../core/QuizCore';
import { WHO_SCENE_IT_PACK } from '../content/quizPacks';

export const WhoSceneItMode = createQuizMode({
  modeId: 'who_scene_it',
  defaultVenueId: 'who_scene_it',
  pack: WHO_SCENE_IT_PACK,
  cfg: WHO_SCENE_IT,
  renderQuestionScene: true,
  foeSkill: 0.6,
  foeSpeed: 0.45,
});
