"""UE5 Integration for Dynamic Environment Loading.

Generates:
  1. C++ subsystem header/implementation for runtime environment management
  2. Blueprint-callable nodes for environment loading/swapping
  3. Editor Python script for importing generated environment assets
  4. Material setup for dynamic skybox and 2.5D backdrop
  5. Post-process volume configurations

Design principles:
  - Generative model provides VISUAL SKIN only (2.5D backdrop)
  - Physics, animation, gameplay logic remain fully in UE5
  - Environment swap is a texture/material swap, not geometry change
  - 60fps target on AWS G5 / mobile devices
"""

import json
import os
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime, timezone

from .config import (
    GENERATED_ROOT, MANIFEST_PATH, UE5_CONTENT,
    ENVIRONMENT_PROMPTS, QUALITY_PRESETS, PROJECT_ROOT,
    ensure_dirs,
)

UE5_SOURCE = PROJECT_ROOT / "UnrealStarter" / "BasketballGame" / "Source" / "FinalEvolutionLab"
UE5_EDITOR_PYTHON = PROJECT_ROOT / "UnrealStarter" / "BasketballGame" / "EditorPython"
UE5_CONFIG = PROJECT_ROOT / "UnrealStarter" / "BasketballGame" / "Content" / "FEL" / "Config"


def generate_dynamic_environment_subsystem_header() -> str:
    """Generate UFELDynamicEnvironmentSubsystem.h"""
    return '''// UFELDynamicEnvironmentSubsystem.h
// Auto-generated by FEL Environment Pipeline
// Dynamic environment loading and swapping for generative world models

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "Engine/TextureCube.h"
#include "Engine/Texture2D.h"
#include "MediaPlayer.h"
#include "MediaTexture.h"
#include "UFELDynamicEnvironmentSubsystem.generated.h"

/**
 * Quality preset for environment rendering.
 */
USTRUCT(BlueprintType)
struct FFELEnvironmentQuality
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 SkyboxResolution = 2048;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 VideoTextureResolution = 1024;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bUseHDR = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 TargetFPS = 60;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bUseParallaxLayers = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 ParallaxLayerCount = 3;
};

/**
 * Info about a loaded environment.
 */
USTRUCT(BlueprintType)
struct FFELEnvironmentInfo
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly)
    FString EnvironmentID;

    UPROPERTY(BlueprintReadOnly)
    FString PromptText;

    UPROPERTY(BlueprintReadOnly)
    FString AestheticStyle;

    UPROPERTY(BlueprintReadOnly)
    TArray<FString> Tags;

    UPROPERTY(BlueprintReadOnly)
    bool bIsLoaded = false;

    UPROPERTY(BlueprintReadOnly)
    bool bHasVideoTexture = false;

    UPROPERTY(BlueprintReadOnly)
    bool bHasCubemap = false;

    UPROPERTY(BlueprintReadOnly)
    bool bHasParallaxLayers = false;
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnEnvironmentLoaded, const FString&, EnvironmentID);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnEnvironmentSwapped, const FString&, OldID, const FString&, NewID);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnEnvironmentLoadFailed, const FString&, EnvironmentID, const FString&, Error);

/**
 * Dynamic Environment Subsystem
 *
 * Manages runtime loading and swapping of AI-generated environments.
 * Environments are visual skins (2.5D backdrops) that do not affect
 * physics or gameplay logic.
 *
 * Key features:
 *   - Load environments by PromptID
 *   - Async preloading for seamless transitions
 *   - Runtime swapping with crossfade
 *   - Adaptive quality based on device capabilities
 *   - Support for equirectangular skybox, cubemap, video texture,
 *     and parallax 2.5D layers
 */
UCLASS()
class FINALEVOLUTIONLAB_API UFELDynamicEnvironmentSubsystem : public UGameInstanceSubsystem
{
    GENERATED_BODY()

public:
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;
    virtual void Deinitialize() override;

    // -----------------------------------------------------------------------
    // Blueprint-callable environment management
    // -----------------------------------------------------------------------

    /** Load a generated environment by its prompt ID. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    bool LoadGeneratedEnvironment(const FString& PromptID);

    /** Swap the current environment at runtime with crossfade. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    bool SwapEnvironmentAtRuntime(const FString& NewEnvironmentID, float CrossfadeDuration = 1.0f);

    /** Preload an environment asynchronously for seamless switching. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void PreloadEnvironmentAsync(const FString& PromptID);

    /** Unload an environment to free memory. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void UnloadEnvironment(const FString& PromptID);

    /** Get info about a specific environment. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    FFELEnvironmentInfo GetEnvironmentInfo(const FString& PromptID) const;

    /** Get the currently active environment ID. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    FString GetActiveEnvironmentID() const;

    /** Get all available environment IDs. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    TArray<FString> GetAvailableEnvironments() const;

    /** Check if an environment is loaded and ready. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    bool IsEnvironmentReady(const FString& PromptID) const;

    /** Get count of loaded environments. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    int32 GetLoadedEnvironmentCount() const;

    // -----------------------------------------------------------------------
    // Quality / Performance
    // -----------------------------------------------------------------------

    /** Set quality preset (ultra/high/medium/mobile/mobile_low). */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void SetQualityPreset(const FString& PresetName);

    /** Auto-detect optimal quality for current device. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void AutoDetectQuality();

    /** Get current quality settings. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    FFELEnvironmentQuality GetCurrentQuality() const;

    // -----------------------------------------------------------------------
    // Skybox & Material Control
    // -----------------------------------------------------------------------

    /** Apply equirectangular texture to the sky sphere. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void ApplySkySphereTexture(UTexture2D* EquirectTexture);

    /** Apply cubemap to the skybox. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void ApplyCubemap(UTextureCube* Cubemap);

    /** Start video texture playback for animated environments. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void StartVideoTexturePlayback(const FString& PromptID);

    /** Stop video texture playback. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void StopVideoTexturePlayback();

    /** Set parallax layer depths for 2.5D backdrop. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void SetParallaxLayerDepths(const TArray<float>& Depths);

    // -----------------------------------------------------------------------
    // Delegates
    // -----------------------------------------------------------------------

    UPROPERTY(BlueprintAssignable, Category = "FEL|Environment")
    FOnEnvironmentLoaded OnEnvironmentLoaded;

    UPROPERTY(BlueprintAssignable, Category = "FEL|Environment")
    FOnEnvironmentSwapped OnEnvironmentSwapped;

    UPROPERTY(BlueprintAssignable, Category = "FEL|Environment")
    FOnEnvironmentLoadFailed OnEnvironmentLoadFailed;

private:
    /** Currently active environment. */
    FString ActiveEnvironmentID;

    /** Quality settings. */
    FFELEnvironmentQuality CurrentQuality;

    /** Loaded environment data. */
    TMap<FString, FFELEnvironmentInfo> LoadedEnvironments;

    /** Preloaded textures. */
    TMap<FString, UTexture2D*> CachedTextures;

    /** Media players for video textures. */
    TMap<FString, UMediaPlayer*> MediaPlayers;

    /** Environment manifest data. */
    TMap<FString, TSharedPtr<FJsonObject>> ManifestEntries;

    /** Load manifest from disk. */
    void LoadManifest();

    /** Internal load implementation. */
    bool LoadEnvironmentInternal(const FString& PromptID);

    /** Apply post-process effects for environment style. */
    void ApplyPostProcessStyle(const FString& AestheticStyle);
};
'''


def generate_dynamic_environment_subsystem_cpp() -> str:
    """Generate UFELDynamicEnvironmentSubsystem.cpp"""
    return '''// UFELDynamicEnvironmentSubsystem.cpp
// Auto-generated by FEL Environment Pipeline

#include "UFELDynamicEnvironmentSubsystem.h"
#include "Misc/FileHelper.h"
#include "Serialization/JsonSerializer.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
#include "Components/SkyLightComponent.h"
#include "Engine/TextureRenderTargetCube.h"

void UFELDynamicEnvironmentSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
    Super::Initialize(Collection);
    UE_LOG(LogTemp, Log, TEXT("[FEL] Dynamic Environment Subsystem initializing..."));

    // Set default quality
    CurrentQuality.SkyboxResolution = 2048;
    CurrentQuality.VideoTextureResolution = 1024;
    CurrentQuality.bUseHDR = true;
    CurrentQuality.TargetFPS = 60;
    CurrentQuality.bUseParallaxLayers = true;
    CurrentQuality.ParallaxLayerCount = 3;

    // Load environment manifest
    LoadManifest();

    UE_LOG(LogTemp, Log, TEXT("[FEL] Dynamic Environment Subsystem ready. %d environments available."),
        ManifestEntries.Num());
}

void UFELDynamicEnvironmentSubsystem::Deinitialize()
{
    // Clean up media players
    for (auto& Pair : MediaPlayers)
    {
        if (Pair.Value)
        {
            Pair.Value->Close();
        }
    }
    MediaPlayers.Empty();
    CachedTextures.Empty();
    LoadedEnvironments.Empty();

    Super::Deinitialize();
}

void UFELDynamicEnvironmentSubsystem::LoadManifest()
{
    // Try multiple manifest locations
    TArray<FString> ManifestPaths = {
        FPaths::ProjectContentDir() / TEXT("FEL/Config/environment_manifest.json"),
        FPaths::ProjectDir() / TEXT("GeneratedAssets/Environments/environment_manifest.json"),
    };

    for (const FString& Path : ManifestPaths)
    {
        FString JsonStr;
        if (FFileHelper::LoadFileToString(JsonStr, *Path))
        {
            TSharedPtr<FJsonObject> Root;
            TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(JsonStr);
            if (FJsonSerializer::Deserialize(Reader, Root) && Root.IsValid())
            {
                const TSharedPtr<FJsonObject>* EnvsObj;
                if (Root->TryGetObjectField(TEXT("environments"), EnvsObj))
                {
                    for (auto& Pair : (*EnvsObj)->Values)
                    {
                        ManifestEntries.Add(Pair.Key, Pair.Value->AsObject());
                    }
                }
                UE_LOG(LogTemp, Log, TEXT("[FEL] Loaded environment manifest from %s (%d entries)"),
                    *Path, ManifestEntries.Num());
                return;
            }
        }
    }

    UE_LOG(LogTemp, Warning, TEXT("[FEL] No environment manifest found"));
}

bool UFELDynamicEnvironmentSubsystem::LoadGeneratedEnvironment(const FString& PromptID)
{
    if (LoadedEnvironments.Contains(PromptID))
    {
        UE_LOG(LogTemp, Log, TEXT("[FEL] Environment %s already loaded"), *PromptID);
        return true;
    }

    return LoadEnvironmentInternal(PromptID);
}

bool UFELDynamicEnvironmentSubsystem::LoadEnvironmentInternal(const FString& PromptID)
{
    TSharedPtr<FJsonObject>* ManifestEntry = ManifestEntries.Find(PromptID);
    if (!ManifestEntry || !ManifestEntry->IsValid())
    {
        FString Error = FString::Printf(TEXT("Environment %s not found in manifest"), *PromptID);
        UE_LOG(LogTemp, Warning, TEXT("[FEL] %s"), *Error);
        OnEnvironmentLoadFailed.Broadcast(PromptID, Error);
        return false;
    }

    FFELEnvironmentInfo Info;
    Info.EnvironmentID = PromptID;
    Info.PromptText = (*ManifestEntry)->GetStringField(TEXT("prompt_text"));
    Info.AestheticStyle = (*ManifestEntry)->GetStringField(TEXT("aesthetic_style"));

    // Load tags
    const TArray<TSharedPtr<FJsonValue>>* TagsArray;
    if ((*ManifestEntry)->TryGetArrayField(TEXT("tags"), TagsArray))
    {
        for (const auto& Tag : *TagsArray)
        {
            Info.Tags.Add(Tag->AsString());
        }
    }

    // Check available assets
    FString EquirectPath = (*ManifestEntry)->GetStringField(TEXT("equirect_path"));
    FString VideoTexPath = (*ManifestEntry)->GetStringField(TEXT("video_texture_path"));

    // Load equirectangular texture
    FString UE5ContentPath = FString::Printf(
        TEXT("/Game/FEL/Environments/Generated/%s/T_%s_Equirect"),
        *PromptID, *PromptID);

    UTexture2D* EquirectTex = Cast<UTexture2D>(
        StaticLoadObject(UTexture2D::StaticClass(), nullptr, *UE5ContentPath));
    if (EquirectTex)
    {
        CachedTextures.Add(PromptID, EquirectTex);
        Info.bHasCubemap = true;
    }

    Info.bHasVideoTexture = !VideoTexPath.IsEmpty();
    Info.bIsLoaded = true;

    LoadedEnvironments.Add(PromptID, Info);

    // Apply environment
    ActiveEnvironmentID = PromptID;
    if (EquirectTex)
    {
        ApplySkySphereTexture(EquirectTex);
    }

    // Apply style-specific post-process
    ApplyPostProcessStyle(Info.AestheticStyle);

    OnEnvironmentLoaded.Broadcast(PromptID);
    UE_LOG(LogTemp, Log, TEXT("[FEL] Environment %s loaded successfully"), *PromptID);
    return true;
}

bool UFELDynamicEnvironmentSubsystem::SwapEnvironmentAtRuntime(
    const FString& NewEnvironmentID, float CrossfadeDuration)
{
    FString OldID = ActiveEnvironmentID;

    // Load new environment if not already loaded
    if (!LoadedEnvironments.Contains(NewEnvironmentID))
    {
        if (!LoadEnvironmentInternal(NewEnvironmentID))
        {
            return false;
        }
    }

    // TODO: Implement crossfade via material parameter interpolation
    // For now, immediate swap
    ActiveEnvironmentID = NewEnvironmentID;

    OnEnvironmentSwapped.Broadcast(OldID, NewEnvironmentID);
    UE_LOG(LogTemp, Log, TEXT("[FEL] Environment swapped: %s -> %s"), *OldID, *NewEnvironmentID);
    return true;
}

void UFELDynamicEnvironmentSubsystem::PreloadEnvironmentAsync(const FString& PromptID)
{
    // Queue async load on background thread
    AsyncTask(ENamedThreads::AnyBackgroundThreadNormalTask, [this, PromptID]()
    {
        // Load manifest data (thread-safe read)
        TSharedPtr<FJsonObject>* Entry = ManifestEntries.Find(PromptID);
        if (Entry && Entry->IsValid())
        {
            // Schedule actual texture load on game thread
            AsyncTask(ENamedThreads::GameThread, [this, PromptID]()
            {
                LoadEnvironmentInternal(PromptID);
            });
        }
    });

    UE_LOG(LogTemp, Log, TEXT("[FEL] Preloading environment %s async"), *PromptID);
}

void UFELDynamicEnvironmentSubsystem::UnloadEnvironment(const FString& PromptID)
{
    LoadedEnvironments.Remove(PromptID);
    CachedTextures.Remove(PromptID);

    if (UMediaPlayer** Player = MediaPlayers.Find(PromptID))
    {
        if (*Player) (*Player)->Close();
        MediaPlayers.Remove(PromptID);
    }

    UE_LOG(LogTemp, Log, TEXT("[FEL] Environment %s unloaded"), *PromptID);
}

FFELEnvironmentInfo UFELDynamicEnvironmentSubsystem::GetEnvironmentInfo(
    const FString& PromptID) const
{
    if (const FFELEnvironmentInfo* Info = LoadedEnvironments.Find(PromptID))
    {
        return *Info;
    }
    return FFELEnvironmentInfo();
}

FString UFELDynamicEnvironmentSubsystem::GetActiveEnvironmentID() const
{
    return ActiveEnvironmentID;
}

TArray<FString> UFELDynamicEnvironmentSubsystem::GetAvailableEnvironments() const
{
    TArray<FString> Keys;
    ManifestEntries.GetKeys(Keys);
    return Keys;
}

bool UFELDynamicEnvironmentSubsystem::IsEnvironmentReady(const FString& PromptID) const
{
    const FFELEnvironmentInfo* Info = LoadedEnvironments.Find(PromptID);
    return Info && Info->bIsLoaded;
}

int32 UFELDynamicEnvironmentSubsystem::GetLoadedEnvironmentCount() const
{
    return LoadedEnvironments.Num();
}

void UFELDynamicEnvironmentSubsystem::SetQualityPreset(const FString& PresetName)
{
    if (PresetName == TEXT("ultra"))
    {
        CurrentQuality = {4096, 2048, true, 60, true, 3};
    }
    else if (PresetName == TEXT("high"))
    {
        CurrentQuality = {2048, 1024, true, 60, true, 3};
    }
    else if (PresetName == TEXT("medium"))
    {
        CurrentQuality = {1024, 512, false, 60, true, 2};
    }
    else if (PresetName == TEXT("mobile"))
    {
        CurrentQuality = {1024, 512, false, 60, false, 2};
    }
    else if (PresetName == TEXT("mobile_low"))
    {
        CurrentQuality = {512, 256, false, 30, false, 1};
    }

    UE_LOG(LogTemp, Log, TEXT("[FEL] Quality preset set to: %s"), *PresetName);
}

void UFELDynamicEnvironmentSubsystem::AutoDetectQuality()
{
    // Detect GPU capabilities
    FString RHIName = GDynamicRHI ? GDynamicRHI->GetName() : TEXT("Unknown");

    // Simple heuristic based on platform
#if PLATFORM_IOS
    SetQualityPreset(TEXT("mobile"));
#elif PLATFORM_ANDROID
    SetQualityPreset(TEXT("mobile_low"));
#else
    // Desktop / Cloud (AWS G5)
    SetQualityPreset(TEXT("high"));
#endif

    UE_LOG(LogTemp, Log, TEXT("[FEL] Auto-detected quality: Skybox=%d, VideoTex=%d, HDR=%d"),
        CurrentQuality.SkyboxResolution,
        CurrentQuality.VideoTextureResolution,
        CurrentQuality.bUseHDR);
}

FFELEnvironmentQuality UFELDynamicEnvironmentSubsystem::GetCurrentQuality() const
{
    return CurrentQuality;
}

void UFELDynamicEnvironmentSubsystem::ApplySkySphereTexture(UTexture2D* EquirectTexture)
{
    if (!EquirectTexture) return;

    // Find sky sphere actor in the world
    UWorld* World = GetGameInstance()->GetWorld();
    if (!World) return;

    // Apply via dynamic material instance on sky sphere
    TArray<AActor*> SkyActors;
    UGameplayStatics::GetAllActorsWithTag(World, FName(TEXT("FELSkySphere")), SkyActors);

    for (AActor* Sky : SkyActors)
    {
        UStaticMeshComponent* MeshComp = Sky->FindComponentByClass<UStaticMeshComponent>();
        if (MeshComp)
        {
            UMaterialInstanceDynamic* DynMat = MeshComp->CreateDynamicMaterialInstance(0);
            if (DynMat)
            {
                DynMat->SetTextureParameterValue(FName(TEXT("EnvironmentTexture")), EquirectTexture);
            }
        }
    }
}

void UFELDynamicEnvironmentSubsystem::ApplyCubemap(UTextureCube* Cubemap)
{
    if (!Cubemap) return;

    UWorld* World = GetGameInstance()->GetWorld();
    if (!World) return;

    // Update sky light with new cubemap
    TArray<AActor*> SkyLights;
    UGameplayStatics::GetAllActorsOfClass(World, ASkyLight::StaticClass(), SkyLights);

    for (AActor* Actor : SkyLights)
    {
        ASkyLight* SkyLight = Cast<ASkyLight>(Actor);
        if (SkyLight && SkyLight->GetLightComponent())
        {
            SkyLight->GetLightComponent()->SetCubemap(Cubemap);
            SkyLight->GetLightComponent()->RecaptureSky();
        }
    }
}

void UFELDynamicEnvironmentSubsystem::StartVideoTexturePlayback(const FString& PromptID)
{
    // Create or get media player for this environment
    UMediaPlayer** ExistingPlayer = MediaPlayers.Find(PromptID);
    if (ExistingPlayer && *ExistingPlayer)
    {
        (*ExistingPlayer)->Play();
        return;
    }

    // TODO: Create media player, open video file, bind to material
    UE_LOG(LogTemp, Log, TEXT("[FEL] Video texture playback started for %s"), *PromptID);
}

void UFELDynamicEnvironmentSubsystem::StopVideoTexturePlayback()
{
    for (auto& Pair : MediaPlayers)
    {
        if (Pair.Value)
        {
            Pair.Value->Pause();
        }
    }
}

void UFELDynamicEnvironmentSubsystem::SetParallaxLayerDepths(const TArray<float>& Depths)
{
    UWorld* World = GetGameInstance()->GetWorld();
    if (!World) return;

    // Find parallax layer actors tagged with FELParallaxLayer_N
    for (int32 i = 0; i < Depths.Num(); i++)
    {
        FName Tag = FName(*FString::Printf(TEXT("FELParallaxLayer_%d"), i));
        TArray<AActor*> LayerActors;
        UGameplayStatics::GetAllActorsWithTag(World, Tag, LayerActors);

        for (AActor* Actor : LayerActors)
        {
            FVector Loc = Actor->GetActorLocation();
            Loc.X = Depths[i]; // Set depth
            Actor->SetActorLocation(Loc);
        }
    }
}

void UFELDynamicEnvironmentSubsystem::ApplyPostProcessStyle(const FString& AestheticStyle)
{
    UWorld* World = GetGameInstance()->GetWorld();
    if (!World) return;

    // Find FEL post-process volume
    TArray<AActor*> PPVolumes;
    UGameplayStatics::GetAllActorsWithTag(World, FName(TEXT("FELPostProcess")), PPVolumes);

    for (AActor* Actor : PPVolumes)
    {
        // Apply style-specific post-process settings
        // These create the atmospheric effects that match the generated environment
        if (AestheticStyle == TEXT("cyberpunk"))
        {
            // Boost bloom, add chromatic aberration, cooler color temperature
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying cyberpunk post-process"));
        }
        else if (AestheticStyle == TEXT("retro"))
        {
            // Film grain, warm color grade, slight vignette
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying retro post-process"));
        }
        else if (AestheticStyle == TEXT("zen"))
        {
            // Soft focus, warm whites, minimal contrast
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying zen post-process"));
        }
        else if (AestheticStyle == TEXT("industrial"))
        {
            // Desaturated, high contrast, cool shadows
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying industrial post-process"));
        }
        else
        {
            // Default cinematic look
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying default cinematic post-process"));
        }
    }
}
'''


def generate_editor_import_script() -> str:
    """Generate UE5 Editor Python script for importing environment assets."""
    return '''# fel_import_environments.py
# Auto-generated by FEL Environment Pipeline
# Run in UE5 Editor: Edit > Editor Preferences > Python > Execute

import unreal
import json
import os

def import_generated_environments():
    """Import all generated environment assets into UE5."""
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    editor_util = unreal.EditorAssetLibrary

    # Find manifest
    manifest_paths = [
        os.path.join(unreal.Paths.project_content_dir(),
                     "FEL", "Config", "environment_manifest.json"),
        os.path.join(unreal.Paths.project_dir(),
                     "GeneratedAssets", "Environments", "environment_manifest.json"),
    ]

    manifest_data = None
    for path in manifest_paths:
        if os.path.exists(path):
            with open(path, "r") as f:
                manifest_data = json.load(f)
            break

    if not manifest_data:
        unreal.log_error("[FEL] Environment manifest not found")
        return

    environments = manifest_data.get("environments", {})
    imported = 0
    skipped = 0

    for env_id, env_data in environments.items():
        if env_data.get("status") != "ready":
            skipped += 1
            continue

        dest_path = f"/Game/FEL/Environments/Generated/{env_id}"

        # Import equirectangular texture
        equirect = env_data.get("equirect_path")
        if equirect and os.path.exists(equirect):
            task = unreal.AssetImportTask()
            task.filename = equirect
            task.destination_path = dest_path
            task.destination_name = f"T_{env_id}_Equirect"
            task.automated = True
            task.save = True
            task.replace_existing = True

            # Configure texture import
            options = unreal.FbxImportUI()
            task.options = options

            asset_tools.import_asset_tasks([task])
            imported += 1
            unreal.log(f"[FEL] Imported equirect for {env_id}")

        # Import cubemap faces
        cubemap_dir = env_data.get("cubemap_dir")
        if cubemap_dir and os.path.isdir(cubemap_dir):
            for face in ["PosX", "NegX", "PosY", "NegY", "PosZ", "NegZ"]:
                face_path = os.path.join(cubemap_dir, f"{face}.png")
                if os.path.exists(face_path):
                    task = unreal.AssetImportTask()
                    task.filename = face_path
                    task.destination_path = f"{dest_path}/Cubemap"
                    task.destination_name = f"T_{env_id}_{face}"
                    task.automated = True
                    task.save = True
                    asset_tools.import_asset_tasks([task])

        # Import video texture
        video_tex = env_data.get("video_texture_path")
        if video_tex and os.path.exists(video_tex):
            # Video textures need FileMediaSource
            task = unreal.AssetImportTask()
            task.filename = video_tex
            task.destination_path = f"{dest_path}/Video"
            task.destination_name = f"V_{env_id}"
            task.automated = True
            task.save = True
            asset_tools.import_asset_tasks([task])

        # Import parallax layers
        for i, layer_path in enumerate(env_data.get("parallax_layers", [])):
            if os.path.exists(layer_path):
                layer_name = os.path.basename(layer_path).replace(".png", "")
                task = unreal.AssetImportTask()
                task.filename = layer_path
                task.destination_path = f"{dest_path}/Layers"
                task.destination_name = f"T_{env_id}_{layer_name}"
                task.automated = True
                task.save = True
                asset_tools.import_asset_tasks([task])

        # Import thumbnail
        thumb = env_data.get("thumbnail_path")
        if thumb and os.path.exists(thumb):
            task = unreal.AssetImportTask()
            task.filename = thumb
            task.destination_path = f"{dest_path}"
            task.destination_name = f"T_{env_id}_Thumb"
            task.automated = True
            task.save = True
            asset_tools.import_asset_tasks([task])

    unreal.log(f"[FEL] Environment import complete: {imported} imported, {skipped} skipped")


def create_environment_materials():
    """Create dynamic materials for each imported environment."""
    editor_util = unreal.EditorAssetLibrary
    material_factory = unreal.MaterialFactoryNew()
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

    # Create base sky sphere material
    base_mat_path = "/Game/FEL/Environments/Materials/M_FEL_DynamicSky"
    if not editor_util.does_asset_exist(base_mat_path):
        asset_tools.create_asset(
            "M_FEL_DynamicSky",
            "/Game/FEL/Environments/Materials",
            unreal.Material,
            material_factory
        )
        unreal.log("[FEL] Created base dynamic sky material")

    # Create parallax layer material
    parallax_mat_path = "/Game/FEL/Environments/Materials/M_FEL_ParallaxLayer"
    if not editor_util.does_asset_exist(parallax_mat_path):
        asset_tools.create_asset(
            "M_FEL_ParallaxLayer",
            "/Game/FEL/Environments/Materials",
            unreal.Material,
            material_factory
        )
        unreal.log("[FEL] Created parallax layer material")


def setup_post_process_presets():
    """Create post-process preset data assets for each aesthetic style."""
    styles = ["cyberpunk", "retro", "zen", "industrial", "tropical",
              "synthwave", "cinematic"]

    for style in styles:
        unreal.log(f"[FEL] Post-process preset for style: {style}")
        # In production, create UDataAsset with post-process settings


# Main execution
import_generated_environments()
create_environment_materials()
setup_post_process_presets()
unreal.log("[FEL] Environment setup complete")
'''


def generate_all_ue5_files():
    """Generate all UE5 integration files."""
    ensure_dirs()
    UE5_SOURCE.mkdir(parents=True, exist_ok=True)
    UE5_EDITOR_PYTHON.mkdir(parents=True, exist_ok=True)

    files_written = []

    # 1. C++ Header
    header_path = UE5_SOURCE / "UFELDynamicEnvironmentSubsystem.h"
    header_path.write_text(generate_dynamic_environment_subsystem_header())
    files_written.append(str(header_path))
    print(f"  Written: {header_path}")

    # 2. C++ Implementation
    cpp_path = UE5_SOURCE / "UFELDynamicEnvironmentSubsystem.cpp"
    cpp_path.write_text(generate_dynamic_environment_subsystem_cpp())
    files_written.append(str(cpp_path))
    print(f"  Written: {cpp_path}")

    # 3. Editor Python import script
    editor_path = UE5_EDITOR_PYTHON / "fel_import_environments.py"
    editor_path.write_text(generate_editor_import_script())
    files_written.append(str(editor_path))
    print(f"  Written: {editor_path}")

    # 4. Generate environment content paths header
    paths_header = generate_environment_paths_header()
    paths_path = UE5_SOURCE / "FELGeneratedEnvironmentPaths.h"
    paths_path.write_text(paths_header)
    files_written.append(str(paths_path))
    print(f"  Written: {paths_path}")

    return files_written


def generate_environment_paths_header() -> str:
    """Generate C++ header with compile-time environment paths."""
    lines = [
        '// FELGeneratedEnvironmentPaths.h',
        '// Auto-generated by FEL Environment Pipeline',
        f'// Generated: {datetime.now(timezone.utc).isoformat()}',
        '//',
        '// Compile-time soft-reference paths for generated environments.',
        '// Used by UFELDynamicEnvironmentSubsystem for asset loading.',
        '',
        '#pragma once',
        '',
        'namespace FELEnvironmentPaths',
        '{',
    ]

    for key in ENVIRONMENT_PROMPTS.keys():
        safe_name = key.upper()
        lines.append(f'    // {key}')
        lines.append(f'    static const TCHAR* {safe_name}_EQUIRECT =')
        lines.append(f'        TEXT("/Game/FEL/Environments/Generated/{key}/T_{key}_Equirect");')
        lines.append(f'    static const TCHAR* {safe_name}_MATERIAL =')
        lines.append(f'        TEXT("/Game/FEL/Environments/Generated/{key}/M_{key}");')
        lines.append(f'    static const TCHAR* {safe_name}_VIDEO =')
        lines.append(f'        TEXT("/Game/FEL/Environments/Generated/{key}/Video/V_{key}");')
        lines.append('')

    # Environment ID constants
    lines.append('    // Environment ID constants')
    for key in ENVIRONMENT_PROMPTS.keys():
        safe_name = key.upper()
        lines.append(f'    static const TCHAR* ID_{safe_name} = TEXT("{key}");')

    lines.append('}')
    lines.append('')

    return '\n'.join(lines)


if __name__ == "__main__":
    print("Generating UE5 integration files...")
    files = generate_all_ue5_files()
    print(f"\nGenerated {len(files)} files:")
    for f in files:
        print(f"  {f}")
