// Auto-generated by ai_asset_pipeline/unreal_import_helper.py
// DO NOT EDIT MANUALLY — re-run the import helper to update.
#pragma once

#include "CoreMinimal.h"

namespace FELGeneratedAssets
{
    // === Exercise Motion Capture Animations ===

    // === Exercise Props (Meshy 3D) ===

    // === Environment Assets (Luma + Meshy) ===
}
