// FELGeneratedEnvironmentPaths.h
// Auto-generated by FEL Environment Pipeline
// Generated: 2026-04-01T23:41:17.329603+00:00
//
// Compile-time soft-reference paths for generated environments.
// Used by UFELDynamicEnvironmentSubsystem for asset loading.

#pragma once

namespace FELEnvironmentPaths
{
    // retro_tokyo_night
    static const TCHAR* RETRO_TOKYO_NIGHT_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/retro_tokyo_night/T_retro_tokyo_night_Equirect");
    static const TCHAR* RETRO_TOKYO_NIGHT_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/retro_tokyo_night/M_retro_tokyo_night");
    static const TCHAR* RETRO_TOKYO_NIGHT_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/retro_tokyo_night/Video/V_retro_tokyo_night");

    // venice_beach_sunset
    static const TCHAR* VENICE_BEACH_SUNSET_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/venice_beach_sunset/T_venice_beach_sunset_Equirect");
    static const TCHAR* VENICE_BEACH_SUNSET_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/venice_beach_sunset/M_venice_beach_sunset");
    static const TCHAR* VENICE_BEACH_SUNSET_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/venice_beach_sunset/Video/V_venice_beach_sunset");

    // cyberpunk_gym
    static const TCHAR* CYBERPUNK_GYM_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/cyberpunk_gym/T_cyberpunk_gym_Equirect");
    static const TCHAR* CYBERPUNK_GYM_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/cyberpunk_gym/M_cyberpunk_gym");
    static const TCHAR* CYBERPUNK_GYM_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/cyberpunk_gym/Video/V_cyberpunk_gym");

    // classic_nba_arena
    static const TCHAR* CLASSIC_NBA_ARENA_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/classic_nba_arena/T_classic_nba_arena_Equirect");
    static const TCHAR* CLASSIC_NBA_ARENA_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/classic_nba_arena/M_classic_nba_arena");
    static const TCHAR* CLASSIC_NBA_ARENA_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/classic_nba_arena/Video/V_classic_nba_arena");

    // underground_bunker
    static const TCHAR* UNDERGROUND_BUNKER_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/underground_bunker/T_underground_bunker_Equirect");
    static const TCHAR* UNDERGROUND_BUNKER_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/underground_bunker/M_underground_bunker");
    static const TCHAR* UNDERGROUND_BUNKER_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/underground_bunker/Video/V_underground_bunker");

    // rooftop_cityscape
    static const TCHAR* ROOFTOP_CITYSCAPE_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/rooftop_cityscape/T_rooftop_cityscape_Equirect");
    static const TCHAR* ROOFTOP_CITYSCAPE_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/rooftop_cityscape/M_rooftop_cityscape");
    static const TCHAR* ROOFTOP_CITYSCAPE_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/rooftop_cityscape/Video/V_rooftop_cityscape");

    // winter_outdoor
    static const TCHAR* WINTER_OUTDOOR_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/winter_outdoor/T_winter_outdoor_Equirect");
    static const TCHAR* WINTER_OUTDOOR_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/winter_outdoor/M_winter_outdoor");
    static const TCHAR* WINTER_OUTDOOR_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/winter_outdoor/Video/V_winter_outdoor");

    // beach_tropical
    static const TCHAR* BEACH_TROPICAL_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/beach_tropical/T_beach_tropical_Equirect");
    static const TCHAR* BEACH_TROPICAL_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/beach_tropical/M_beach_tropical");
    static const TCHAR* BEACH_TROPICAL_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/beach_tropical/Video/V_beach_tropical");

    // warehouse_industrial
    static const TCHAR* WAREHOUSE_INDUSTRIAL_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/warehouse_industrial/T_warehouse_industrial_Equirect");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/warehouse_industrial/M_warehouse_industrial");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/warehouse_industrial/Video/V_warehouse_industrial");

    // neon_arcade
    static const TCHAR* NEON_ARCADE_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/neon_arcade/T_neon_arcade_Equirect");
    static const TCHAR* NEON_ARCADE_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/neon_arcade/M_neon_arcade");
    static const TCHAR* NEON_ARCADE_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/neon_arcade/Video/V_neon_arcade");

    // zen_dojo
    static const TCHAR* ZEN_DOJO_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/zen_dojo/T_zen_dojo_Equirect");
    static const TCHAR* ZEN_DOJO_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/zen_dojo/M_zen_dojo");
    static const TCHAR* ZEN_DOJO_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/zen_dojo/Video/V_zen_dojo");

    // stadium_night_game
    static const TCHAR* STADIUM_NIGHT_GAME_EQUIRECT =
        TEXT("/Game/FEL/Environments/Generated/stadium_night_game/T_stadium_night_game_Equirect");
    static const TCHAR* STADIUM_NIGHT_GAME_MATERIAL =
        TEXT("/Game/FEL/Environments/Generated/stadium_night_game/M_stadium_night_game");
    static const TCHAR* STADIUM_NIGHT_GAME_VIDEO =
        TEXT("/Game/FEL/Environments/Generated/stadium_night_game/Video/V_stadium_night_game");

    // Environment ID constants
    static const TCHAR* ID_RETRO_TOKYO_NIGHT = TEXT("retro_tokyo_night");
    static const TCHAR* ID_VENICE_BEACH_SUNSET = TEXT("venice_beach_sunset");
    static const TCHAR* ID_CYBERPUNK_GYM = TEXT("cyberpunk_gym");
    static const TCHAR* ID_CLASSIC_NBA_ARENA = TEXT("classic_nba_arena");
    static const TCHAR* ID_UNDERGROUND_BUNKER = TEXT("underground_bunker");
    static const TCHAR* ID_ROOFTOP_CITYSCAPE = TEXT("rooftop_cityscape");
    static const TCHAR* ID_WINTER_OUTDOOR = TEXT("winter_outdoor");
    static const TCHAR* ID_BEACH_TROPICAL = TEXT("beach_tropical");
    static const TCHAR* ID_WAREHOUSE_INDUSTRIAL = TEXT("warehouse_industrial");
    static const TCHAR* ID_NEON_ARCADE = TEXT("neon_arcade");
    static const TCHAR* ID_ZEN_DOJO = TEXT("zen_dojo");
    static const TCHAR* ID_STADIUM_NIGHT_GAME = TEXT("stadium_night_game");
}
