// =============================================================================
// FELOpenArtAssetPaths.h — Auto-generated by OpenArt Enhanced Pipeline
// DO NOT EDIT MANUALLY — regenerate with openart_enhanced_pipeline.py
// Total environments: 12
// Total asset entries: 360
// =============================================================================
#pragma once

namespace FELOpenArtAssets
{

    // ----- beach_tropical -----
    // props
    static const TCHAR* BEACH_TROPICAL_PROPS_BAMBOO_FENCE = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/bamboo_fence");
    static const TCHAR* BEACH_TROPICAL_PROPS_BANANA_PLANT = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/banana_plant");
    static const TCHAR* BEACH_TROPICAL_PROPS_BEACH_CHAIR = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/beach_chair");
    static const TCHAR* BEACH_TROPICAL_PROPS_BEACH_UMBRELLA = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/beach_umbrella");
    static const TCHAR* BEACH_TROPICAL_PROPS_BOAT_BEACHED = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/boat_beached");
    static const TCHAR* BEACH_TROPICAL_PROPS_COCONUT_PALM = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/coconut_palm");
    static const TCHAR* BEACH_TROPICAL_PROPS_COOLER_BOX = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/cooler_box");
    static const TCHAR* BEACH_TROPICAL_PROPS_CORAL_DECORATION = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/coral_decoration");
    static const TCHAR* BEACH_TROPICAL_PROPS_HAMMOCK = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/hammock");
    static const TCHAR* BEACH_TROPICAL_PROPS_SURFBOARD_01 = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/surfboard_01");
    static const TCHAR* BEACH_TROPICAL_PROPS_TIKI_TORCH = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/tiki_torch");
    static const TCHAR* BEACH_TROPICAL_PROPS_VOLLEYBALL_NET = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/props/volleyball_net");
    // textures
    static const TCHAR* BEACH_TROPICAL_TEXTURES_BAMBOO_MAT = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/textures/bamboo_mat");
    static const TCHAR* BEACH_TROPICAL_TEXTURES_CORAL_STONE = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/textures/coral_stone");
    static const TCHAR* BEACH_TROPICAL_TEXTURES_PALM_BARK = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/textures/palm_bark");
    static const TCHAR* BEACH_TROPICAL_TEXTURES_WET_SAND = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/textures/wet_sand");
    static const TCHAR* BEACH_TROPICAL_TEXTURES_WHITE_SAND = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/textures/white_sand");
    // materials
    static const TCHAR* BEACH_TROPICAL_MATERIALS_TROPICAL_WOOD = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/materials/tropical_wood");
    static const TCHAR* BEACH_TROPICAL_MATERIALS_WET_SAND_MATERIAL = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/materials/wet_sand_material");
    static const TCHAR* BEACH_TROPICAL_MATERIALS_WOVEN_PALM = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/materials/woven_palm");
    // atmosphere
    static const TCHAR* BEACH_TROPICAL_ATMOSPHERE_OCEAN_MIST = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/atmosphere/ocean_mist");
    static const TCHAR* BEACH_TROPICAL_ATMOSPHERE_SUN_SPARKLE = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/atmosphere/sun_sparkle");
    static const TCHAR* BEACH_TROPICAL_ATMOSPHERE_TROPICAL_RAYS = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/atmosphere/tropical_rays");
    // skybox
    static const TCHAR* BEACH_TROPICAL_SKYBOX_TROPICAL_STORM = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/skybox/tropical_storm");
    static const TCHAR* BEACH_TROPICAL_SKYBOX_TROPICAL_SUNNY = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/skybox/tropical_sunny");
    static const TCHAR* BEACH_TROPICAL_SKYBOX_TROPICAL_SUNSET = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/skybox/tropical_sunset");
    // details
    static const TCHAR* BEACH_TROPICAL_DETAILS_COCONUT_FALLEN = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/details/coconut_fallen");
    static const TCHAR* BEACH_TROPICAL_DETAILS_CRAB_TRACKS = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/details/crab_tracks");
    static const TCHAR* BEACH_TROPICAL_DETAILS_SHELL_SCATTER = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/details/shell_scatter");
    static const TCHAR* BEACH_TROPICAL_DETAILS_WAVE_FOAM = TEXT("/Game/FEL/Environments/OpenArt/beach_tropical/details/wave_foam");

    // ----- classic_nba_arena -----
    // props
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_ARENA_SPEAKER = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/arena_speaker");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_BANNER_CHAMPIONSHIP = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/banner_championship");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_BASKET_STANCHION = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/basket_stanchion");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_BASKETBALL_RACK = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/basketball_rack");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_CAMERA_PLATFORM = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/camera_platform");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_COURTSIDE_SEAT = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/courtside_seat");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_JUMBOTRON = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/jumbotron");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_PRESS_ROW_DESK = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/press_row_desk");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_SCORERS_TABLE = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/scorers_table");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_SHOT_CLOCK = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/shot_clock");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_TEAM_BENCH = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/team_bench");
    static const TCHAR* CLASSIC_NBA_ARENA_PROPS_WATER_COOLER = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/props/water_cooler");
    // textures
    static const TCHAR* CLASSIC_NBA_ARENA_TEXTURES_ARENA_SEAT_FABRIC = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/textures/arena_seat_fabric");
    static const TCHAR* CLASSIC_NBA_ARENA_TEXTURES_CONCRETE_CONCOURSE = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/textures/concrete_concourse");
    static const TCHAR* CLASSIC_NBA_ARENA_TEXTURES_HARDWOOD_COURT = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/textures/hardwood_court");
    static const TCHAR* CLASSIC_NBA_ARENA_TEXTURES_PADDED_WALL = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/textures/padded_wall");
    static const TCHAR* CLASSIC_NBA_ARENA_TEXTURES_PAINTED_LANE = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/textures/painted_lane");
    // materials
    static const TCHAR* CLASSIC_NBA_ARENA_MATERIALS_ARENA_METAL = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/materials/arena_metal");
    static const TCHAR* CLASSIC_NBA_ARENA_MATERIALS_LEATHER_BALL = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/materials/leather_ball");
    static const TCHAR* CLASSIC_NBA_ARENA_MATERIALS_POLISHED_HARDWOOD = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/materials/polished_hardwood");
    // atmosphere
    static const TCHAR* CLASSIC_NBA_ARENA_ATMOSPHERE_CROWD_DUST = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/atmosphere/crowd_dust");
    static const TCHAR* CLASSIC_NBA_ARENA_ATMOSPHERE_SPOTLIGHT_BEAMS = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/atmosphere/spotlight_beams");
    static const TCHAR* CLASSIC_NBA_ARENA_ATMOSPHERE_SPOTLIGHT_HAZE = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/atmosphere/spotlight_haze");
    // skybox
    static const TCHAR* CLASSIC_NBA_ARENA_SKYBOX_ARENA_CEILING = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/skybox/arena_ceiling");
    static const TCHAR* CLASSIC_NBA_ARENA_SKYBOX_ARENA_CROWD = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/skybox/arena_crowd");
    static const TCHAR* CLASSIC_NBA_ARENA_SKYBOX_ARENA_DARK = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/skybox/arena_dark");
    // details
    static const TCHAR* CLASSIC_NBA_ARENA_DETAILS_SHOE_SCUFF = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/details/shoe_scuff");
    static const TCHAR* CLASSIC_NBA_ARENA_DETAILS_SPONSOR_DECAL = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/details/sponsor_decal");
    static const TCHAR* CLASSIC_NBA_ARENA_DETAILS_SWEAT_STAIN = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/details/sweat_stain");
    static const TCHAR* CLASSIC_NBA_ARENA_DETAILS_TAPE_LINE = TEXT("/Game/FEL/Environments/OpenArt/classic_nba_arena/details/tape_line");

    // ----- cyberpunk_gym -----
    // props
    static const TCHAR* CYBERPUNK_GYM_PROPS_CYBER_BENCH_PRESS = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/cyber_bench_press");
    static const TCHAR* CYBERPUNK_GYM_PROPS_DRONE_CAMERA = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/drone_camera");
    static const TCHAR* CYBERPUNK_GYM_PROPS_ENERGY_DRINK_VENDING = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/energy_drink_vending");
    static const TCHAR* CYBERPUNK_GYM_PROPS_FLOOR_LIGHT_STRIP = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/floor_light_strip");
    static const TCHAR* CYBERPUNK_GYM_PROPS_HOLOGRAM_DISPLAY = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/hologram_display");
    static const TCHAR* CYBERPUNK_GYM_PROPS_LOCKER_BANK = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/locker_bank");
    static const TCHAR* CYBERPUNK_GYM_PROPS_NEON_TUBE_01 = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/neon_tube_01");
    static const TCHAR* CYBERPUNK_GYM_PROPS_POWER_CABLE_BUNDLE = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/power_cable_bundle");
    static const TCHAR* CYBERPUNK_GYM_PROPS_PUNCHING_BAG_LED = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/punching_bag_led");
    static const TCHAR* CYBERPUNK_GYM_PROPS_SCORE_SCREEN = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/score_screen");
    static const TCHAR* CYBERPUNK_GYM_PROPS_TRAINING_POD = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/training_pod");
    static const TCHAR* CYBERPUNK_GYM_PROPS_WEIGHT_RACK_CYBER = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/props/weight_rack_cyber");
    // textures
    static const TCHAR* CYBERPUNK_GYM_TEXTURES_BRUSHED_CHROME = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/textures/brushed_chrome");
    static const TCHAR* CYBERPUNK_GYM_TEXTURES_CARBON_FIBER = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/textures/carbon_fiber");
    static const TCHAR* CYBERPUNK_GYM_TEXTURES_CIRCUIT_WALL = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/textures/circuit_wall");
    static const TCHAR* CYBERPUNK_GYM_TEXTURES_HEX_FLOOR = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/textures/hex_floor");
    static const TCHAR* CYBERPUNK_GYM_TEXTURES_RUBBER_FLOOR = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/textures/rubber_floor");
    // materials
    static const TCHAR* CYBERPUNK_GYM_MATERIALS_DARK_COMPOSITE = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/materials/dark_composite");
    static const TCHAR* CYBERPUNK_GYM_MATERIALS_LED_PANEL = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/materials/led_panel");
    static const TCHAR* CYBERPUNK_GYM_MATERIALS_NEON_CHROME = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/materials/neon_chrome");
    // atmosphere
    static const TCHAR* CYBERPUNK_GYM_ATMOSPHERE_CYBER_HAZE = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/atmosphere/cyber_haze");
    static const TCHAR* CYBERPUNK_GYM_ATMOSPHERE_HOLOGRAM_PARTICLES = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/atmosphere/hologram_particles");
    static const TCHAR* CYBERPUNK_GYM_ATMOSPHERE_NEON_LIGHT_BLOOM = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/atmosphere/neon_light_bloom");
    // skybox
    static const TCHAR* CYBERPUNK_GYM_SKYBOX_CYBER_CITY_NIGHT = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/skybox/cyber_city_night");
    static const TCHAR* CYBERPUNK_GYM_SKYBOX_CYBER_INTERIOR = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/skybox/cyber_interior");
    static const TCHAR* CYBERPUNK_GYM_SKYBOX_CYBER_STORM = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/skybox/cyber_storm");
    // details
    static const TCHAR* CYBERPUNK_GYM_DETAILS_IMPACT_CRACK = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/details/impact_crack");
    static const TCHAR* CYBERPUNK_GYM_DETAILS_QR_CODE_STICKER = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/details/qr_code_sticker");
    static const TCHAR* CYBERPUNK_GYM_DETAILS_TECH_GRAFFITI = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/details/tech_graffiti");
    static const TCHAR* CYBERPUNK_GYM_DETAILS_WARNING_LABEL = TEXT("/Game/FEL/Environments/OpenArt/cyberpunk_gym/details/warning_label");

    // ----- neon_arcade -----
    // props
    static const TCHAR* NEON_ARCADE_PROPS_ARCADE_CABINET = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/arcade_cabinet");
    static const TCHAR* NEON_ARCADE_PROPS_BASKETBALL_ARCADE = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/basketball_arcade");
    static const TCHAR* NEON_ARCADE_PROPS_CLAW_MACHINE = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/claw_machine");
    static const TCHAR* NEON_ARCADE_PROPS_DISCO_BALL = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/disco_ball");
    static const TCHAR* NEON_ARCADE_PROPS_JUKEBOX = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/jukebox");
    static const TCHAR* NEON_ARCADE_PROPS_LED_WALL_PANEL = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/led_wall_panel");
    static const TCHAR* NEON_ARCADE_PROPS_NEON_GRID_PANEL = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/neon_grid_panel");
    static const TCHAR* NEON_ARCADE_PROPS_NEON_PALM = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/neon_palm");
    static const TCHAR* NEON_ARCADE_PROPS_PINBALL_MACHINE = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/pinball_machine");
    static const TCHAR* NEON_ARCADE_PROPS_PIXEL_SCOREBOARD = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/pixel_scoreboard");
    static const TCHAR* NEON_ARCADE_PROPS_RACING_SEAT = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/racing_seat");
    static const TCHAR* NEON_ARCADE_PROPS_TOKEN_DISPENSER = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/props/token_dispenser");
    // textures
    static const TCHAR* NEON_ARCADE_TEXTURES_CHROME_PANEL = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/textures/chrome_panel");
    static const TCHAR* NEON_ARCADE_TEXTURES_LED_STRIP_WALL = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/textures/led_strip_wall");
    static const TCHAR* NEON_ARCADE_TEXTURES_NEON_GRID_FLOOR = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/textures/neon_grid_floor");
    static const TCHAR* NEON_ARCADE_TEXTURES_PIXEL_TILE = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/textures/pixel_tile");
    static const TCHAR* NEON_ARCADE_TEXTURES_RUBBER_ARCADE_FLOOR = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/textures/rubber_arcade_floor");
    // materials
    static const TCHAR* NEON_ARCADE_MATERIALS_GLOWING_GRID = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/materials/glowing_grid");
    static const TCHAR* NEON_ARCADE_MATERIALS_NEON_GLASS = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/materials/neon_glass");
    static const TCHAR* NEON_ARCADE_MATERIALS_RETRO_CHROME = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/materials/retro_chrome");
    // atmosphere
    static const TCHAR* NEON_ARCADE_ATMOSPHERE_LASER_BEAMS = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/atmosphere/laser_beams");
    static const TCHAR* NEON_ARCADE_ATMOSPHERE_NEON_HAZE = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/atmosphere/neon_haze");
    static const TCHAR* NEON_ARCADE_ATMOSPHERE_SPARKLE_PARTICLES = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/atmosphere/sparkle_particles");
    // skybox
    static const TCHAR* NEON_ARCADE_SKYBOX_ARCADE_CEILING = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/skybox/arcade_ceiling");
    static const TCHAR* NEON_ARCADE_SKYBOX_DIGITAL_VOID = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/skybox/digital_void");
    static const TCHAR* NEON_ARCADE_SKYBOX_SYNTHWAVE_SKY = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/skybox/synthwave_sky");
    // details
    static const TCHAR* NEON_ARCADE_DETAILS_GUM_WAD = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/details/gum_wad");
    static const TCHAR* NEON_ARCADE_DETAILS_HIGH_SCORE_LIST = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/details/high_score_list");
    static const TCHAR* NEON_ARCADE_DETAILS_NEON_CRACK = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/details/neon_crack");
    static const TCHAR* NEON_ARCADE_DETAILS_PIXEL_STICKER = TEXT("/Game/FEL/Environments/OpenArt/neon_arcade/details/pixel_sticker");

    // ----- retro_tokyo_night -----
    // props
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_BENCH_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/bench_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_BIKE_RACK_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/bike_rack_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_GRAFFITI_WALL_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/graffiti_wall_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_MANHOLE_COVER_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/manhole_cover_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_NEON_SIGN_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/neon_sign_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_PHONE_BOOTH_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/phone_booth_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_POWER_LINES_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/power_lines_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_RAMEN_CART_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/ramen_cart_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_SHRINE_GATE_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/shrine_gate_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_STREET_LAMP_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/street_lamp_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_TRASH_CAN_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/trash_can_01");
    static const TCHAR* RETRO_TOKYO_NIGHT_PROPS_VENDING_MACHINE_01 = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/props/vending_machine_01");
    // textures
    static const TCHAR* RETRO_TOKYO_NIGHT_TEXTURES_BRICK_ALLEY = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/textures/brick_alley");
    static const TCHAR* RETRO_TOKYO_NIGHT_TEXTURES_CONCRETE_WALL = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/textures/concrete_wall");
    static const TCHAR* RETRO_TOKYO_NIGHT_TEXTURES_METAL_SHUTTER = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/textures/metal_shutter");
    static const TCHAR* RETRO_TOKYO_NIGHT_TEXTURES_TILE_FLOOR = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/textures/tile_floor");
    static const TCHAR* RETRO_TOKYO_NIGHT_TEXTURES_WET_ASPHALT = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/textures/wet_asphalt");
    // materials
    static const TCHAR* RETRO_TOKYO_NIGHT_MATERIALS_GRAFFITI_BRICK = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/materials/graffiti_brick");
    static const TCHAR* RETRO_TOKYO_NIGHT_MATERIALS_NEON_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/materials/neon_concrete");
    static const TCHAR* RETRO_TOKYO_NIGHT_MATERIALS_WET_METAL = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/materials/wet_metal");
    // atmosphere
    static const TCHAR* RETRO_TOKYO_NIGHT_ATMOSPHERE_LIGHT_RAYS_NEON = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/atmosphere/light_rays_neon");
    static const TCHAR* RETRO_TOKYO_NIGHT_ATMOSPHERE_NEON_FOG = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/atmosphere/neon_fog");
    static const TCHAR* RETRO_TOKYO_NIGHT_ATMOSPHERE_RAIN_PARTICLES = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/atmosphere/rain_particles");
    // skybox
    static const TCHAR* RETRO_TOKYO_NIGHT_SKYBOX_TOKYO_NIGHT_CLEAR = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/skybox/tokyo_night_clear");
    static const TCHAR* RETRO_TOKYO_NIGHT_SKYBOX_TOKYO_NIGHT_HAZE = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/skybox/tokyo_night_haze");
    static const TCHAR* RETRO_TOKYO_NIGHT_SKYBOX_TOKYO_NIGHT_RAIN = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/skybox/tokyo_night_rain");
    // details
    static const TCHAR* RETRO_TOKYO_NIGHT_DETAILS_CRACK_PATTERN = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/details/crack_pattern");
    static const TCHAR* RETRO_TOKYO_NIGHT_DETAILS_KANJI_STENCIL = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/details/kanji_stencil");
    static const TCHAR* RETRO_TOKYO_NIGHT_DETAILS_POSTER_TORN = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/details/poster_torn");
    static const TCHAR* RETRO_TOKYO_NIGHT_DETAILS_PUDDLE_REFLECTION = TEXT("/Game/FEL/Environments/OpenArt/retro_tokyo_night/details/puddle_reflection");

    // ----- rooftop_cityscape -----
    // props
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_AC_UNIT = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/ac_unit");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_CHAIN_LINK_FENCE = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/chain_link_fence");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_FIRE_ESCAPE = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/fire_escape");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_FOLDING_TABLE = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/folding_table");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_GRAFFITI_ROOFTOP = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/graffiti_rooftop");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_PIGEON_COOP = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/pigeon_coop");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_PORTABLE_HOOP = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/portable_hoop");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_RADIO_ANTENNA = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/radio_antenna");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_ROOFTOP_LIGHT = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/rooftop_light");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_SATELLITE_DISH = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/satellite_dish");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_VENTILATION_DUCT = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/ventilation_duct");
    static const TCHAR* ROOFTOP_CITYSCAPE_PROPS_WATER_TOWER = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/props/water_tower");
    // textures
    static const TCHAR* ROOFTOP_CITYSCAPE_TEXTURES_BRICK_PARAPET = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/textures/brick_parapet");
    static const TCHAR* ROOFTOP_CITYSCAPE_TEXTURES_GRAVEL_ROOF = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/textures/gravel_roof");
    static const TCHAR* ROOFTOP_CITYSCAPE_TEXTURES_METAL_GRATING = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/textures/metal_grating");
    static const TCHAR* ROOFTOP_CITYSCAPE_TEXTURES_PAINTED_COURT_ROOF = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/textures/painted_court_roof");
    static const TCHAR* ROOFTOP_CITYSCAPE_TEXTURES_TAR_ROOF = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/textures/tar_roof");
    // materials
    static const TCHAR* ROOFTOP_CITYSCAPE_MATERIALS_FADED_PAINT = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/materials/faded_paint");
    static const TCHAR* ROOFTOP_CITYSCAPE_MATERIALS_GALVANIZED_STEEL = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/materials/galvanized_steel");
    static const TCHAR* ROOFTOP_CITYSCAPE_MATERIALS_WEATHERED_TAR = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/materials/weathered_tar");
    // atmosphere
    static const TCHAR* ROOFTOP_CITYSCAPE_ATMOSPHERE_CITY_HAZE = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/atmosphere/city_haze");
    static const TCHAR* ROOFTOP_CITYSCAPE_ATMOSPHERE_SUNSET_RAYS_CITY = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/atmosphere/sunset_rays_city");
    static const TCHAR* ROOFTOP_CITYSCAPE_ATMOSPHERE_WIND_DUST = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/atmosphere/wind_dust");
    // skybox
    static const TCHAR* ROOFTOP_CITYSCAPE_SKYBOX_CITY_DUSK = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/skybox/city_dusk");
    static const TCHAR* ROOFTOP_CITYSCAPE_SKYBOX_CITY_GOLDEN = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/skybox/city_golden");
    static const TCHAR* ROOFTOP_CITYSCAPE_SKYBOX_CITY_NIGHT = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/skybox/city_night");
    // details
    static const TCHAR* ROOFTOP_CITYSCAPE_DETAILS_CIGARETTE_BUTTS = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/details/cigarette_butts");
    static const TCHAR* ROOFTOP_CITYSCAPE_DETAILS_PIGEON_DROPPINGS = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/details/pigeon_droppings");
    static const TCHAR* ROOFTOP_CITYSCAPE_DETAILS_ROOF_PATCH = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/details/roof_patch");
    static const TCHAR* ROOFTOP_CITYSCAPE_DETAILS_TAG_SPRAYPAINT = TEXT("/Game/FEL/Environments/OpenArt/rooftop_cityscape/details/tag_spraypaint");

    // ----- stadium_night_game -----
    // props
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_BALL_BOY_CHAIR = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/ball_boy_chair");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_BARRIER_FENCE = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/barrier_fence");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_CAMERA_CRANE = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/camera_crane");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_COACH_BENCH = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/coach_bench");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_CORNER_FLAG = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/corner_flag");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_ELECTRONIC_BOARD = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/electronic_board");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_FLOODLIGHT_TOWER = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/floodlight_tower");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_GOAL_POST = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/goal_post");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_PYRO_FIREWORK = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/pyro_firework");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_STRETCHER = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/stretcher");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_TUNNEL_ENTRANCE = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/tunnel_entrance");
    static const TCHAR* STADIUM_NIGHT_GAME_PROPS_VAR_SCREEN = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/props/var_screen");
    // textures
    static const TCHAR* STADIUM_NIGHT_GAME_TEXTURES_ASTROTURF = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/textures/astroturf");
    static const TCHAR* STADIUM_NIGHT_GAME_TEXTURES_CONCRETE_TERRACE = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/textures/concrete_terrace");
    static const TCHAR* STADIUM_NIGHT_GAME_TEXTURES_GRASS_PITCH = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/textures/grass_pitch");
    static const TCHAR* STADIUM_NIGHT_GAME_TEXTURES_PAINTED_GRASS = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/textures/painted_grass");
    static const TCHAR* STADIUM_NIGHT_GAME_TEXTURES_RUNNING_TRACK = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/textures/running_track");
    // materials
    static const TCHAR* STADIUM_NIGHT_GAME_MATERIALS_MATCH_GRASS = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/materials/match_grass");
    static const TCHAR* STADIUM_NIGHT_GAME_MATERIALS_SPONSOR_VINYL = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/materials/sponsor_vinyl");
    static const TCHAR* STADIUM_NIGHT_GAME_MATERIALS_STADIUM_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/materials/stadium_concrete");
    // atmosphere
    static const TCHAR* STADIUM_NIGHT_GAME_ATMOSPHERE_CROWD_SMOKE = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/atmosphere/crowd_smoke");
    static const TCHAR* STADIUM_NIGHT_GAME_ATMOSPHERE_FLOODLIGHT_HAZE = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/atmosphere/floodlight_haze");
    static const TCHAR* STADIUM_NIGHT_GAME_ATMOSPHERE_HALFTIME_FIREWORKS = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/atmosphere/halftime_fireworks");
    // skybox
    static const TCHAR* STADIUM_NIGHT_GAME_SKYBOX_STADIUM_FIREWORKS = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/skybox/stadium_fireworks");
    static const TCHAR* STADIUM_NIGHT_GAME_SKYBOX_STADIUM_NIGHT = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/skybox/stadium_night");
    static const TCHAR* STADIUM_NIGHT_GAME_SKYBOX_STADIUM_PACKED = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/skybox/stadium_packed");
    // details
    static const TCHAR* STADIUM_NIGHT_GAME_DETAILS_BOOT_MUD = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/details/boot_mud");
    static const TCHAR* STADIUM_NIGHT_GAME_DETAILS_CONFETTI_SCATTER = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/details/confetti_scatter");
    static const TCHAR* STADIUM_NIGHT_GAME_DETAILS_PITCH_DIVOT = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/details/pitch_divot");
    static const TCHAR* STADIUM_NIGHT_GAME_DETAILS_SPONSOR_LOGO = TEXT("/Game/FEL/Environments/OpenArt/stadium_night_game/details/sponsor_logo");

    // ----- underground_bunker -----
    // props
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_AMMO_CRATE = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/ammo_crate");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_BATTLE_ROPES = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/battle_ropes");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_CHALK_BUCKET = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/chalk_bucket");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_FLOODLIGHT = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/floodlight");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_HEAVY_BAG = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/heavy_bag");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_MILITARY_LOCKER = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/military_locker");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_MOTIVATIONAL_SIGN = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/motivational_sign");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_PULL_UP_BAR = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/pull_up_bar");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_SPEED_BAG = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/speed_bag");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_TIRE_STACK = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/tire_stack");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_VENTILATION_FAN = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/ventilation_fan");
    static const TCHAR* UNDERGROUND_BUNKER_PROPS_WATER_PIPE = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/props/water_pipe");
    // textures
    static const TCHAR* UNDERGROUND_BUNKER_TEXTURES_CINDER_BLOCK = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/textures/cinder_block");
    static const TCHAR* UNDERGROUND_BUNKER_TEXTURES_MILITARY_FLOOR = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/textures/military_floor");
    static const TCHAR* UNDERGROUND_BUNKER_TEXTURES_RAW_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/textures/raw_concrete");
    static const TCHAR* UNDERGROUND_BUNKER_TEXTURES_RUBBER_MAT = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/textures/rubber_mat");
    static const TCHAR* UNDERGROUND_BUNKER_TEXTURES_RUSTED_METAL = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/textures/rusted_metal");
    // materials
    static const TCHAR* UNDERGROUND_BUNKER_MATERIALS_BUNKER_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/materials/bunker_concrete");
    static const TCHAR* UNDERGROUND_BUNKER_MATERIALS_OXIDIZED_STEEL = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/materials/oxidized_steel");
    static const TCHAR* UNDERGROUND_BUNKER_MATERIALS_WORN_RUBBER = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/materials/worn_rubber");
    // atmosphere
    static const TCHAR* UNDERGROUND_BUNKER_ATMOSPHERE_CHALK_DUST = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/atmosphere/chalk_dust");
    static const TCHAR* UNDERGROUND_BUNKER_ATMOSPHERE_CONDENSATION_FOG = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/atmosphere/condensation_fog");
    static const TCHAR* UNDERGROUND_BUNKER_ATMOSPHERE_HARSH_SPOTLIGHT = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/atmosphere/harsh_spotlight");
    // skybox
    static const TCHAR* UNDERGROUND_BUNKER_SKYBOX_BUNKER_CEILING = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/skybox/bunker_ceiling");
    static const TCHAR* UNDERGROUND_BUNKER_SKYBOX_BUNKER_DARK = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/skybox/bunker_dark");
    static const TCHAR* UNDERGROUND_BUNKER_SKYBOX_BUNKER_LIT = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/skybox/bunker_lit");
    // details
    static const TCHAR* UNDERGROUND_BUNKER_DETAILS_CHALK_HANDPRINT = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/details/chalk_handprint");
    static const TCHAR* UNDERGROUND_BUNKER_DETAILS_RUST_DRIP = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/details/rust_drip");
    static const TCHAR* UNDERGROUND_BUNKER_DETAILS_STENCIL_MARKING = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/details/stencil_marking");
    static const TCHAR* UNDERGROUND_BUNKER_DETAILS_WATER_STAIN = TEXT("/Game/FEL/Environments/OpenArt/underground_bunker/details/water_stain");

    // ----- venice_beach_sunset -----
    // props
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_BASKETBALL_HOOP_OUTDOOR = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/basketball_hoop_outdoor");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_BEACH_BENCH = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/beach_bench");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_BEACH_SPEAKER = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/beach_speaker");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_BIKE_PATH_SIGN = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/bike_path_sign");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_GRAFFITI_WALL_VENICE = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/graffiti_wall_venice");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_LIFEGUARD_TOWER = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/lifeguard_tower");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_MUSCLE_BEACH_SIGN = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/muscle_beach_sign");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_PALM_TREE_01 = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/palm_tree_01");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_PALM_TREE_02 = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/palm_tree_02");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_SKATEBOARD_RAMP = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/skateboard_ramp");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_SURFBOARD_RACK = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/surfboard_rack");
    static const TCHAR* VENICE_BEACH_SUNSET_PROPS_TACO_TRUCK = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/props/taco_truck");
    // textures
    static const TCHAR* VENICE_BEACH_SUNSET_TEXTURES_ASPHALT_PATH = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/textures/asphalt_path");
    static const TCHAR* VENICE_BEACH_SUNSET_TEXTURES_BEACH_SAND = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/textures/beach_sand");
    static const TCHAR* VENICE_BEACH_SUNSET_TEXTURES_BOARDWALK_WOOD = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/textures/boardwalk_wood");
    static const TCHAR* VENICE_BEACH_SUNSET_TEXTURES_CONCRETE_COURT = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/textures/concrete_court");
    static const TCHAR* VENICE_BEACH_SUNSET_TEXTURES_STUCCO_WALL = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/textures/stucco_wall");
    // materials
    static const TCHAR* VENICE_BEACH_SUNSET_MATERIALS_BEACH_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/materials/beach_concrete");
    static const TCHAR* VENICE_BEACH_SUNSET_MATERIALS_RUSTY_CHAIN_LINK = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/materials/rusty_chain_link");
    static const TCHAR* VENICE_BEACH_SUNSET_MATERIALS_SUN_BLEACHED_WOOD = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/materials/sun_bleached_wood");
    // atmosphere
    static const TCHAR* VENICE_BEACH_SUNSET_ATMOSPHERE_DUST_PARTICLES = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/atmosphere/dust_particles");
    static const TCHAR* VENICE_BEACH_SUNSET_ATMOSPHERE_GOLDEN_HAZE = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/atmosphere/golden_haze");
    static const TCHAR* VENICE_BEACH_SUNSET_ATMOSPHERE_SUNSET_RAYS = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/atmosphere/sunset_rays");
    // skybox
    static const TCHAR* VENICE_BEACH_SUNSET_SKYBOX_VENICE_DUSK = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/skybox/venice_dusk");
    static const TCHAR* VENICE_BEACH_SUNSET_SKYBOX_VENICE_GOLDEN_HOUR = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/skybox/venice_golden_hour");
    static const TCHAR* VENICE_BEACH_SUNSET_SKYBOX_VENICE_SUNSET_01 = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/skybox/venice_sunset_01");
    // details
    static const TCHAR* VENICE_BEACH_SUNSET_DETAILS_COURT_LINE_PAINT = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/details/court_line_paint");
    static const TCHAR* VENICE_BEACH_SUNSET_DETAILS_SAND_FOOTPRINTS = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/details/sand_footprints");
    static const TCHAR* VENICE_BEACH_SUNSET_DETAILS_SHELL_SCATTER = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/details/shell_scatter");
    static const TCHAR* VENICE_BEACH_SUNSET_DETAILS_SURF_STICKER = TEXT("/Game/FEL/Environments/OpenArt/venice_beach_sunset/details/surf_sticker");

    // ----- warehouse_industrial -----
    // props
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_BOXING_RING = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/boxing_ring");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_CAGE_LIGHT = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/cage_light");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_CHAIN_HOIST = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/chain_hoist");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_CONCRETE_PILLAR = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/concrete_pillar");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_FIRE_EXTINGUISHER = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/fire_extinguisher");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_FORKLIFT = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/forklift");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_LOADING_DOCK = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/loading_dock");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_METAL_SHELF = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/metal_shelf");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_OIL_DRUM = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/oil_drum");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_PALLET_STACK = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/pallet_stack");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_SPRAY_BOOTH = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/spray_booth");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_PROPS_STEEL_BEAM = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/props/steel_beam");
    // textures
    static const TCHAR* WAREHOUSE_INDUSTRIAL_TEXTURES_CONCRETE_FLOOR_PAINTED = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/textures/concrete_floor_painted");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_TEXTURES_CORRUGATED_METAL = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/textures/corrugated_metal");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_TEXTURES_EXPOSED_BRICK = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/textures/exposed_brick");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_TEXTURES_ROUGH_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/textures/rough_concrete");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_TEXTURES_WOOD_PLANK_FLOOR = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/textures/wood_plank_floor");
    // materials
    static const TCHAR* WAREHOUSE_INDUSTRIAL_MATERIALS_AGED_BRICK = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/materials/aged_brick");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_MATERIALS_INDUSTRIAL_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/materials/industrial_concrete");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_MATERIALS_PAINTED_STEEL = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/materials/painted_steel");
    // atmosphere
    static const TCHAR* WAREHOUSE_INDUSTRIAL_ATMOSPHERE_LIGHT_SHAFTS = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/atmosphere/light_shafts");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_ATMOSPHERE_SMOKE_WISPS = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/atmosphere/smoke_wisps");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_ATMOSPHERE_WAREHOUSE_HAZE = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/atmosphere/warehouse_haze");
    // skybox
    static const TCHAR* WAREHOUSE_INDUSTRIAL_SKYBOX_WAREHOUSE_CEILING = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/skybox/warehouse_ceiling");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_SKYBOX_WAREHOUSE_DARK = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/skybox/warehouse_dark");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_SKYBOX_WAREHOUSE_WINDOWS = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/skybox/warehouse_windows");
    // details
    static const TCHAR* WAREHOUSE_INDUSTRIAL_DETAILS_BOOT_SCUFF = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/details/boot_scuff");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_DETAILS_CHALK_TALLY = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/details/chalk_tally");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_DETAILS_OIL_STAIN = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/details/oil_stain");
    static const TCHAR* WAREHOUSE_INDUSTRIAL_DETAILS_PAINT_DRIP = TEXT("/Game/FEL/Environments/OpenArt/warehouse_industrial/details/paint_drip");

    // ----- winter_outdoor -----
    // props
    static const TCHAR* WINTER_OUTDOOR_PROPS_BARE_TREE_01 = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/bare_tree_01");
    static const TCHAR* WINTER_OUTDOOR_PROPS_BARE_TREE_02 = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/bare_tree_02");
    static const TCHAR* WINTER_OUTDOOR_PROPS_CHAIN_HOOP_FROZEN = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/chain_hoop_frozen");
    static const TCHAR* WINTER_OUTDOOR_PROPS_EVERGREEN_TREE = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/evergreen_tree");
    static const TCHAR* WINTER_OUTDOOR_PROPS_FIRE_BARREL = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/fire_barrel");
    static const TCHAR* WINTER_OUTDOOR_PROPS_HOT_CHOCOLATE_CART = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/hot_chocolate_cart");
    static const TCHAR* WINTER_OUTDOOR_PROPS_ICE_FORMATION = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/ice_formation");
    static const TCHAR* WINTER_OUTDOOR_PROPS_PARK_FENCE = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/park_fence");
    static const TCHAR* WINTER_OUTDOOR_PROPS_SNOW_BENCH = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/snow_bench");
    static const TCHAR* WINTER_OUTDOOR_PROPS_SNOW_PILE = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/snow_pile");
    static const TCHAR* WINTER_OUTDOOR_PROPS_SNOW_SHOVEL = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/snow_shovel");
    static const TCHAR* WINTER_OUTDOOR_PROPS_STREET_LAMP_WARM = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/props/street_lamp_warm");
    // textures
    static const TCHAR* WINTER_OUTDOOR_TEXTURES_FROZEN_ASPHALT = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/textures/frozen_asphalt");
    static const TCHAR* WINTER_OUTDOOR_TEXTURES_ICY_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/textures/icy_concrete");
    static const TCHAR* WINTER_OUTDOOR_TEXTURES_SLUSH_PUDDLE = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/textures/slush_puddle");
    static const TCHAR* WINTER_OUTDOOR_TEXTURES_SNOW_BRICK = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/textures/snow_brick");
    static const TCHAR* WINTER_OUTDOOR_TEXTURES_SNOW_GROUND = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/textures/snow_ground");
    // materials
    static const TCHAR* WINTER_OUTDOOR_MATERIALS_FROST_METAL = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/materials/frost_metal");
    static const TCHAR* WINTER_OUTDOOR_MATERIALS_SNOW_CRUST = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/materials/snow_crust");
    static const TCHAR* WINTER_OUTDOOR_MATERIALS_WET_FROZEN_CONCRETE = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/materials/wet_frozen_concrete");
    // atmosphere
    static const TCHAR* WINTER_OUTDOOR_ATMOSPHERE_BREATH_FOG = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/atmosphere/breath_fog");
    static const TCHAR* WINTER_OUTDOOR_ATMOSPHERE_SNOWFALL = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/atmosphere/snowfall");
    static const TCHAR* WINTER_OUTDOOR_ATMOSPHERE_WARM_GLOW = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/atmosphere/warm_glow");
    // skybox
    static const TCHAR* WINTER_OUTDOOR_SKYBOX_WINTER_CLEAR = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/skybox/winter_clear");
    static const TCHAR* WINTER_OUTDOOR_SKYBOX_WINTER_OVERCAST = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/skybox/winter_overcast");
    static const TCHAR* WINTER_OUTDOOR_SKYBOX_WINTER_STORM = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/skybox/winter_storm");
    // details
    static const TCHAR* WINTER_OUTDOOR_DETAILS_BOOT_PRINTS = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/details/boot_prints");
    static const TCHAR* WINTER_OUTDOOR_DETAILS_FROST_PATTERN = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/details/frost_pattern");
    static const TCHAR* WINTER_OUTDOOR_DETAILS_ICICLE_DRIP = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/details/icicle_drip");
    static const TCHAR* WINTER_OUTDOOR_DETAILS_TIRE_TRACKS_SNOW = TEXT("/Game/FEL/Environments/OpenArt/winter_outdoor/details/tire_tracks_snow");

    // ----- zen_dojo -----
    // props
    static const TCHAR* ZEN_DOJO_PROPS_BAMBOO_FOUNTAIN = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/bamboo_fountain");
    static const TCHAR* ZEN_DOJO_PROPS_BONSAI_TREE = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/bonsai_tree");
    static const TCHAR* ZEN_DOJO_PROPS_CALLIGRAPHY_SCROLL = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/calligraphy_scroll");
    static const TCHAR* ZEN_DOJO_PROPS_INCENSE_HOLDER = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/incense_holder");
    static const TCHAR* ZEN_DOJO_PROPS_MEDITATION_CUSHION = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/meditation_cushion");
    static const TCHAR* ZEN_DOJO_PROPS_PAPER_SCREEN = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/paper_screen");
    static const TCHAR* ZEN_DOJO_PROPS_ROUND_WINDOW = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/round_window");
    static const TCHAR* ZEN_DOJO_PROPS_STONE_LANTERN = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/stone_lantern");
    static const TCHAR* ZEN_DOJO_PROPS_TEA_SET = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/tea_set");
    static const TCHAR* ZEN_DOJO_PROPS_TOKONOMA_ALCOVE = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/tokonoma_alcove");
    static const TCHAR* ZEN_DOJO_PROPS_WOODEN_GETA = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/wooden_geta");
    static const TCHAR* ZEN_DOJO_PROPS_WOODEN_RACK = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/props/wooden_rack");
    // textures
    static const TCHAR* ZEN_DOJO_TEXTURES_BAMBOO_SURFACE = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/textures/bamboo_surface");
    static const TCHAR* ZEN_DOJO_TEXTURES_PAPER_WALL = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/textures/paper_wall");
    static const TCHAR* ZEN_DOJO_TEXTURES_STONE_GARDEN = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/textures/stone_garden");
    static const TCHAR* ZEN_DOJO_TEXTURES_TATAMI_MAT = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/textures/tatami_mat");
    static const TCHAR* ZEN_DOJO_TEXTURES_WOOD_BEAM = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/textures/wood_beam");
    // materials
    static const TCHAR* ZEN_DOJO_MATERIALS_AGED_WOOD = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/materials/aged_wood");
    static const TCHAR* ZEN_DOJO_MATERIALS_GARDEN_STONE = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/materials/garden_stone");
    static const TCHAR* ZEN_DOJO_MATERIALS_WASHI_PAPER = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/materials/washi_paper");
    // atmosphere
    static const TCHAR* ZEN_DOJO_ATMOSPHERE_DUST_MOTES_LIGHT = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/atmosphere/dust_motes_light");
    static const TCHAR* ZEN_DOJO_ATMOSPHERE_INCENSE_SMOKE = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/atmosphere/incense_smoke");
    static const TCHAR* ZEN_DOJO_ATMOSPHERE_WARM_GLOW = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/atmosphere/warm_glow");
    // skybox
    static const TCHAR* ZEN_DOJO_SKYBOX_DOJO_INTERIOR = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/skybox/dojo_interior");
    static const TCHAR* ZEN_DOJO_SKYBOX_ZEN_GARDEN_VIEW = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/skybox/zen_garden_view");
    static const TCHAR* ZEN_DOJO_SKYBOX_ZEN_SUNSET = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/skybox/zen_sunset");
    // details
    static const TCHAR* ZEN_DOJO_DETAILS_CALLIGRAPHY_MARK = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/details/calligraphy_mark");
    static const TCHAR* ZEN_DOJO_DETAILS_FLOWER_PETAL = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/details/flower_petal");
    static const TCHAR* ZEN_DOJO_DETAILS_SCRATCH_BAMBOO = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/details/scratch_bamboo");
    static const TCHAR* ZEN_DOJO_DETAILS_TEA_STAIN = TEXT("/Game/FEL/Environments/OpenArt/zen_dojo/details/tea_stain");

    // ----- Environment Keys -----
    static const TCHAR* ENV_BEACH_TROPICAL = TEXT("beach_tropical");
    static const TCHAR* ENV_CLASSIC_NBA_ARENA = TEXT("classic_nba_arena");
    static const TCHAR* ENV_CYBERPUNK_GYM = TEXT("cyberpunk_gym");
    static const TCHAR* ENV_NEON_ARCADE = TEXT("neon_arcade");
    static const TCHAR* ENV_RETRO_TOKYO_NIGHT = TEXT("retro_tokyo_night");
    static const TCHAR* ENV_ROOFTOP_CITYSCAPE = TEXT("rooftop_cityscape");
    static const TCHAR* ENV_STADIUM_NIGHT_GAME = TEXT("stadium_night_game");
    static const TCHAR* ENV_UNDERGROUND_BUNKER = TEXT("underground_bunker");
    static const TCHAR* ENV_VENICE_BEACH_SUNSET = TEXT("venice_beach_sunset");
    static const TCHAR* ENV_WAREHOUSE_INDUSTRIAL = TEXT("warehouse_industrial");
    static const TCHAR* ENV_WINTER_OUTDOOR = TEXT("winter_outdoor");
    static const TCHAR* ENV_ZEN_DOJO = TEXT("zen_dojo");

    // ----- Category Count Constants -----
    static constexpr int32 NUM_ENVIRONMENTS = 12;
    static constexpr int32 TOTAL_ASSET_ENTRIES = 360;
    static constexpr int32 ASSETS_PER_ENVIRONMENT = 30;
}
