// UFELDynamicEnvironmentSubsystem.h
// Auto-generated by FEL Environment Pipeline
// Dynamic environment loading and swapping for generative world models

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "Engine/TextureCube.h"
#include "Engine/Texture2D.h"
#include "MediaPlayer.h"
#include "MediaTexture.h"
#include "UFELDynamicEnvironmentSubsystem.generated.h"

/**
 * Quality preset for environment rendering.
 */
USTRUCT(BlueprintType)
struct FFELEnvironmentQuality
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 SkyboxResolution = 2048;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 VideoTextureResolution = 1024;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bUseHDR = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 TargetFPS = 60;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool bUseParallaxLayers = true;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 ParallaxLayerCount = 3;
};

/**
 * Info about a loaded environment.
 */
USTRUCT(BlueprintType)
struct FFELEnvironmentInfo
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadOnly)
    FString EnvironmentID;

    UPROPERTY(BlueprintReadOnly)
    FString PromptText;

    UPROPERTY(BlueprintReadOnly)
    FString AestheticStyle;

    UPROPERTY(BlueprintReadOnly)
    TArray<FString> Tags;

    UPROPERTY(BlueprintReadOnly)
    bool bIsLoaded = false;

    UPROPERTY(BlueprintReadOnly)
    bool bHasVideoTexture = false;

    UPROPERTY(BlueprintReadOnly)
    bool bHasCubemap = false;

    UPROPERTY(BlueprintReadOnly)
    bool bHasParallaxLayers = false;
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnEnvironmentLoaded, const FString&, EnvironmentID);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnEnvironmentSwapped, const FString&, OldID, const FString&, NewID);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnEnvironmentLoadFailed, const FString&, EnvironmentID, const FString&, Error);

/**
 * Dynamic Environment Subsystem
 *
 * Manages runtime loading and swapping of AI-generated environments.
 * Environments are visual skins (2.5D backdrops) that do not affect
 * physics or gameplay logic.
 *
 * Key features:
 *   - Load environments by PromptID
 *   - Async preloading for seamless transitions
 *   - Runtime swapping with crossfade
 *   - Adaptive quality based on device capabilities
 *   - Support for equirectangular skybox, cubemap, video texture,
 *     and parallax 2.5D layers
 */
UCLASS()
class FINALEVOLUTIONLAB_API UFELDynamicEnvironmentSubsystem : public UGameInstanceSubsystem
{
    GENERATED_BODY()

public:
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;
    virtual void Deinitialize() override;

    // -----------------------------------------------------------------------
    // Blueprint-callable environment management
    // -----------------------------------------------------------------------

    /** Load a generated environment by its prompt ID. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    bool LoadGeneratedEnvironment(const FString& PromptID);

    /** Swap the current environment at runtime with crossfade. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    bool SwapEnvironmentAtRuntime(const FString& NewEnvironmentID, float CrossfadeDuration = 1.0f);

    /** Preload an environment asynchronously for seamless switching. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void PreloadEnvironmentAsync(const FString& PromptID);

    /** Unload an environment to free memory. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void UnloadEnvironment(const FString& PromptID);

    /** Get info about a specific environment. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    FFELEnvironmentInfo GetEnvironmentInfo(const FString& PromptID) const;

    /** Get the currently active environment ID. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    FString GetActiveEnvironmentID() const;

    /** Get all available environment IDs. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    TArray<FString> GetAvailableEnvironments() const;

    /** Check if an environment is loaded and ready. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    bool IsEnvironmentReady(const FString& PromptID) const;

    /** Get count of loaded environments. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    int32 GetLoadedEnvironmentCount() const;

    // -----------------------------------------------------------------------
    // Quality / Performance
    // -----------------------------------------------------------------------

    /** Set quality preset (ultra/high/medium/mobile/mobile_low). */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void SetQualityPreset(const FString& PresetName);

    /** Auto-detect optimal quality for current device. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void AutoDetectQuality();

    /** Get current quality settings. */
    UFUNCTION(BlueprintCallable, BlueprintPure, Category = "FEL|Environment")
    FFELEnvironmentQuality GetCurrentQuality() const;

    // -----------------------------------------------------------------------
    // Skybox & Material Control
    // -----------------------------------------------------------------------

    /** Apply equirectangular texture to the sky sphere. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void ApplySkySphereTexture(UTexture2D* EquirectTexture);

    /** Apply cubemap to the skybox. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void ApplyCubemap(UTextureCube* Cubemap);

    /** Start video texture playback for animated environments. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void StartVideoTexturePlayback(const FString& PromptID);

    /** Stop video texture playback. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void StopVideoTexturePlayback();

    /** Set parallax layer depths for 2.5D backdrop. */
    UFUNCTION(BlueprintCallable, Category = "FEL|Environment")
    void SetParallaxLayerDepths(const TArray<float>& Depths);

    // -----------------------------------------------------------------------
    // Delegates
    // -----------------------------------------------------------------------

    UPROPERTY(BlueprintAssignable, Category = "FEL|Environment")
    FOnEnvironmentLoaded OnEnvironmentLoaded;

    UPROPERTY(BlueprintAssignable, Category = "FEL|Environment")
    FOnEnvironmentSwapped OnEnvironmentSwapped;

    UPROPERTY(BlueprintAssignable, Category = "FEL|Environment")
    FOnEnvironmentLoadFailed OnEnvironmentLoadFailed;

private:
    /** Currently active environment. */
    FString ActiveEnvironmentID;

    /** Quality settings. */
    FFELEnvironmentQuality CurrentQuality;

    /** Loaded environment data. */
    TMap<FString, FFELEnvironmentInfo> LoadedEnvironments;

    /** Preloaded textures. */
    TMap<FString, UTexture2D*> CachedTextures;

    /** Media players for video textures. */
    TMap<FString, UMediaPlayer*> MediaPlayers;

    /** Environment manifest data. */
    TMap<FString, TSharedPtr<FJsonObject>> ManifestEntries;

    /** Load manifest from disk. */
    void LoadManifest();

    /** Internal load implementation. */
    bool LoadEnvironmentInternal(const FString& PromptID);

    /** Apply post-process effects for environment style. */
    void ApplyPostProcessStyle(const FString& AestheticStyle);
};
