// UFELDynamicEnvironmentSubsystem.cpp
// Auto-generated by FEL Environment Pipeline

#include "UFELDynamicEnvironmentSubsystem.h"
#include "Misc/FileHelper.h"
#include "Serialization/JsonSerializer.h"
#include "Engine/Engine.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
#include "Components/SkyLightComponent.h"
#include "Engine/TextureRenderTargetCube.h"

void UFELDynamicEnvironmentSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{
    Super::Initialize(Collection);
    UE_LOG(LogTemp, Log, TEXT("[FEL] Dynamic Environment Subsystem initializing..."));

    // Set default quality
    CurrentQuality.SkyboxResolution = 2048;
    CurrentQuality.VideoTextureResolution = 1024;
    CurrentQuality.bUseHDR = true;
    CurrentQuality.TargetFPS = 60;
    CurrentQuality.bUseParallaxLayers = true;
    CurrentQuality.ParallaxLayerCount = 3;

    // Load environment manifest
    LoadManifest();

    UE_LOG(LogTemp, Log, TEXT("[FEL] Dynamic Environment Subsystem ready. %d environments available."),
        ManifestEntries.Num());
}

void UFELDynamicEnvironmentSubsystem::Deinitialize()
{
    // Clean up media players
    for (auto& Pair : MediaPlayers)
    {
        if (Pair.Value)
        {
            Pair.Value->Close();
        }
    }
    MediaPlayers.Empty();
    CachedTextures.Empty();
    LoadedEnvironments.Empty();

    Super::Deinitialize();
}

void UFELDynamicEnvironmentSubsystem::LoadManifest()
{
    // Try multiple manifest locations
    TArray<FString> ManifestPaths = {
        FPaths::ProjectContentDir() / TEXT("FEL/Config/environment_manifest.json"),
        FPaths::ProjectDir() / TEXT("GeneratedAssets/Environments/environment_manifest.json"),
    };

    for (const FString& Path : ManifestPaths)
    {
        FString JsonStr;
        if (FFileHelper::LoadFileToString(JsonStr, *Path))
        {
            TSharedPtr<FJsonObject> Root;
            TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(JsonStr);
            if (FJsonSerializer::Deserialize(Reader, Root) && Root.IsValid())
            {
                const TSharedPtr<FJsonObject>* EnvsObj;
                if (Root->TryGetObjectField(TEXT("environments"), EnvsObj))
                {
                    for (auto& Pair : (*EnvsObj)->Values)
                    {
                        ManifestEntries.Add(Pair.Key, Pair.Value->AsObject());
                    }
                }
                UE_LOG(LogTemp, Log, TEXT("[FEL] Loaded environment manifest from %s (%d entries)"),
                    *Path, ManifestEntries.Num());
                return;
            }
        }
    }

    UE_LOG(LogTemp, Warning, TEXT("[FEL] No environment manifest found"));
}

bool UFELDynamicEnvironmentSubsystem::LoadGeneratedEnvironment(const FString& PromptID)
{
    if (LoadedEnvironments.Contains(PromptID))
    {
        UE_LOG(LogTemp, Log, TEXT("[FEL] Environment %s already loaded"), *PromptID);
        return true;
    }

    return LoadEnvironmentInternal(PromptID);
}

bool UFELDynamicEnvironmentSubsystem::LoadEnvironmentInternal(const FString& PromptID)
{
    TSharedPtr<FJsonObject>* ManifestEntry = ManifestEntries.Find(PromptID);
    if (!ManifestEntry || !ManifestEntry->IsValid())
    {
        FString Error = FString::Printf(TEXT("Environment %s not found in manifest"), *PromptID);
        UE_LOG(LogTemp, Warning, TEXT("[FEL] %s"), *Error);
        OnEnvironmentLoadFailed.Broadcast(PromptID, Error);
        return false;
    }

    FFELEnvironmentInfo Info;
    Info.EnvironmentID = PromptID;
    Info.PromptText = (*ManifestEntry)->GetStringField(TEXT("prompt_text"));
    Info.AestheticStyle = (*ManifestEntry)->GetStringField(TEXT("aesthetic_style"));

    // Load tags
    const TArray<TSharedPtr<FJsonValue>>* TagsArray;
    if ((*ManifestEntry)->TryGetArrayField(TEXT("tags"), TagsArray))
    {
        for (const auto& Tag : *TagsArray)
        {
            Info.Tags.Add(Tag->AsString());
        }
    }

    // Check available assets
    FString EquirectPath = (*ManifestEntry)->GetStringField(TEXT("equirect_path"));
    FString VideoTexPath = (*ManifestEntry)->GetStringField(TEXT("video_texture_path"));

    // Load equirectangular texture
    FString UE5ContentPath = FString::Printf(
        TEXT("/Game/FEL/Environments/Generated/%s/T_%s_Equirect"),
        *PromptID, *PromptID);

    UTexture2D* EquirectTex = Cast<UTexture2D>(
        StaticLoadObject(UTexture2D::StaticClass(), nullptr, *UE5ContentPath));
    if (EquirectTex)
    {
        CachedTextures.Add(PromptID, EquirectTex);
        Info.bHasCubemap = true;
    }

    Info.bHasVideoTexture = !VideoTexPath.IsEmpty();
    Info.bIsLoaded = true;

    LoadedEnvironments.Add(PromptID, Info);

    // Apply environment
    ActiveEnvironmentID = PromptID;
    if (EquirectTex)
    {
        ApplySkySphereTexture(EquirectTex);
    }

    // Apply style-specific post-process
    ApplyPostProcessStyle(Info.AestheticStyle);

    OnEnvironmentLoaded.Broadcast(PromptID);
    UE_LOG(LogTemp, Log, TEXT("[FEL] Environment %s loaded successfully"), *PromptID);
    return true;
}

bool UFELDynamicEnvironmentSubsystem::SwapEnvironmentAtRuntime(
    const FString& NewEnvironmentID, float CrossfadeDuration)
{
    FString OldID = ActiveEnvironmentID;

    // Load new environment if not already loaded
    if (!LoadedEnvironments.Contains(NewEnvironmentID))
    {
        if (!LoadEnvironmentInternal(NewEnvironmentID))
        {
            return false;
        }
    }

    // TODO: Implement crossfade via material parameter interpolation
    // For now, immediate swap
    ActiveEnvironmentID = NewEnvironmentID;

    OnEnvironmentSwapped.Broadcast(OldID, NewEnvironmentID);
    UE_LOG(LogTemp, Log, TEXT("[FEL] Environment swapped: %s -> %s"), *OldID, *NewEnvironmentID);
    return true;
}

void UFELDynamicEnvironmentSubsystem::PreloadEnvironmentAsync(const FString& PromptID)
{
    // Queue async load on background thread
    AsyncTask(ENamedThreads::AnyBackgroundThreadNormalTask, [this, PromptID]()
    {
        // Load manifest data (thread-safe read)
        TSharedPtr<FJsonObject>* Entry = ManifestEntries.Find(PromptID);
        if (Entry && Entry->IsValid())
        {
            // Schedule actual texture load on game thread
            AsyncTask(ENamedThreads::GameThread, [this, PromptID]()
            {
                LoadEnvironmentInternal(PromptID);
            });
        }
    });

    UE_LOG(LogTemp, Log, TEXT("[FEL] Preloading environment %s async"), *PromptID);
}

void UFELDynamicEnvironmentSubsystem::UnloadEnvironment(const FString& PromptID)
{
    LoadedEnvironments.Remove(PromptID);
    CachedTextures.Remove(PromptID);

    if (UMediaPlayer** Player = MediaPlayers.Find(PromptID))
    {
        if (*Player) (*Player)->Close();
        MediaPlayers.Remove(PromptID);
    }

    UE_LOG(LogTemp, Log, TEXT("[FEL] Environment %s unloaded"), *PromptID);
}

FFELEnvironmentInfo UFELDynamicEnvironmentSubsystem::GetEnvironmentInfo(
    const FString& PromptID) const
{
    if (const FFELEnvironmentInfo* Info = LoadedEnvironments.Find(PromptID))
    {
        return *Info;
    }
    return FFELEnvironmentInfo();
}

FString UFELDynamicEnvironmentSubsystem::GetActiveEnvironmentID() const
{
    return ActiveEnvironmentID;
}

TArray<FString> UFELDynamicEnvironmentSubsystem::GetAvailableEnvironments() const
{
    TArray<FString> Keys;
    ManifestEntries.GetKeys(Keys);
    return Keys;
}

bool UFELDynamicEnvironmentSubsystem::IsEnvironmentReady(const FString& PromptID) const
{
    const FFELEnvironmentInfo* Info = LoadedEnvironments.Find(PromptID);
    return Info && Info->bIsLoaded;
}

int32 UFELDynamicEnvironmentSubsystem::GetLoadedEnvironmentCount() const
{
    return LoadedEnvironments.Num();
}

void UFELDynamicEnvironmentSubsystem::SetQualityPreset(const FString& PresetName)
{
    if (PresetName == TEXT("ultra"))
    {
        CurrentQuality = {4096, 2048, true, 60, true, 3};
    }
    else if (PresetName == TEXT("high"))
    {
        CurrentQuality = {2048, 1024, true, 60, true, 3};
    }
    else if (PresetName == TEXT("medium"))
    {
        CurrentQuality = {1024, 512, false, 60, true, 2};
    }
    else if (PresetName == TEXT("mobile"))
    {
        CurrentQuality = {1024, 512, false, 60, false, 2};
    }
    else if (PresetName == TEXT("mobile_low"))
    {
        CurrentQuality = {512, 256, false, 30, false, 1};
    }

    UE_LOG(LogTemp, Log, TEXT("[FEL] Quality preset set to: %s"), *PresetName);
}

void UFELDynamicEnvironmentSubsystem::AutoDetectQuality()
{
    // Detect GPU capabilities
    FString RHIName = GDynamicRHI ? GDynamicRHI->GetName() : TEXT("Unknown");

    // Simple heuristic based on platform
#if PLATFORM_IOS
    SetQualityPreset(TEXT("mobile"));
#elif PLATFORM_ANDROID
    SetQualityPreset(TEXT("mobile_low"));
#else
    // Desktop / Cloud (AWS G5)
    SetQualityPreset(TEXT("high"));
#endif

    UE_LOG(LogTemp, Log, TEXT("[FEL] Auto-detected quality: Skybox=%d, VideoTex=%d, HDR=%d"),
        CurrentQuality.SkyboxResolution,
        CurrentQuality.VideoTextureResolution,
        CurrentQuality.bUseHDR);
}

FFELEnvironmentQuality UFELDynamicEnvironmentSubsystem::GetCurrentQuality() const
{
    return CurrentQuality;
}

void UFELDynamicEnvironmentSubsystem::ApplySkySphereTexture(UTexture2D* EquirectTexture)
{
    if (!EquirectTexture) return;

    // Find sky sphere actor in the world
    UWorld* World = GetGameInstance()->GetWorld();
    if (!World) return;

    // Apply via dynamic material instance on sky sphere
    TArray<AActor*> SkyActors;
    UGameplayStatics::GetAllActorsWithTag(World, FName(TEXT("FELSkySphere")), SkyActors);

    for (AActor* Sky : SkyActors)
    {
        UStaticMeshComponent* MeshComp = Sky->FindComponentByClass<UStaticMeshComponent>();
        if (MeshComp)
        {
            UMaterialInstanceDynamic* DynMat = MeshComp->CreateDynamicMaterialInstance(0);
            if (DynMat)
            {
                DynMat->SetTextureParameterValue(FName(TEXT("EnvironmentTexture")), EquirectTexture);
            }
        }
    }
}

void UFELDynamicEnvironmentSubsystem::ApplyCubemap(UTextureCube* Cubemap)
{
    if (!Cubemap) return;

    UWorld* World = GetGameInstance()->GetWorld();
    if (!World) return;

    // Update sky light with new cubemap
    TArray<AActor*> SkyLights;
    UGameplayStatics::GetAllActorsOfClass(World, ASkyLight::StaticClass(), SkyLights);

    for (AActor* Actor : SkyLights)
    {
        ASkyLight* SkyLight = Cast<ASkyLight>(Actor);
        if (SkyLight && SkyLight->GetLightComponent())
        {
            SkyLight->GetLightComponent()->SetCubemap(Cubemap);
            SkyLight->GetLightComponent()->RecaptureSky();
        }
    }
}

void UFELDynamicEnvironmentSubsystem::StartVideoTexturePlayback(const FString& PromptID)
{
    // Create or get media player for this environment
    UMediaPlayer** ExistingPlayer = MediaPlayers.Find(PromptID);
    if (ExistingPlayer && *ExistingPlayer)
    {
        (*ExistingPlayer)->Play();
        return;
    }

    // TODO: Create media player, open video file, bind to material
    UE_LOG(LogTemp, Log, TEXT("[FEL] Video texture playback started for %s"), *PromptID);
}

void UFELDynamicEnvironmentSubsystem::StopVideoTexturePlayback()
{
    for (auto& Pair : MediaPlayers)
    {
        if (Pair.Value)
        {
            Pair.Value->Pause();
        }
    }
}

void UFELDynamicEnvironmentSubsystem::SetParallaxLayerDepths(const TArray<float>& Depths)
{
    UWorld* World = GetGameInstance()->GetWorld();
    if (!World) return;

    // Find parallax layer actors tagged with FELParallaxLayer_N
    for (int32 i = 0; i < Depths.Num(); i++)
    {
        FName Tag = FName(*FString::Printf(TEXT("FELParallaxLayer_%d"), i));
        TArray<AActor*> LayerActors;
        UGameplayStatics::GetAllActorsWithTag(World, Tag, LayerActors);

        for (AActor* Actor : LayerActors)
        {
            FVector Loc = Actor->GetActorLocation();
            Loc.X = Depths[i]; // Set depth
            Actor->SetActorLocation(Loc);
        }
    }
}

void UFELDynamicEnvironmentSubsystem::ApplyPostProcessStyle(const FString& AestheticStyle)
{
    UWorld* World = GetGameInstance()->GetWorld();
    if (!World) return;

    // Find FEL post-process volume
    TArray<AActor*> PPVolumes;
    UGameplayStatics::GetAllActorsWithTag(World, FName(TEXT("FELPostProcess")), PPVolumes);

    for (AActor* Actor : PPVolumes)
    {
        // Apply style-specific post-process settings
        // These create the atmospheric effects that match the generated environment
        if (AestheticStyle == TEXT("cyberpunk"))
        {
            // Boost bloom, add chromatic aberration, cooler color temperature
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying cyberpunk post-process"));
        }
        else if (AestheticStyle == TEXT("retro"))
        {
            // Film grain, warm color grade, slight vignette
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying retro post-process"));
        }
        else if (AestheticStyle == TEXT("zen"))
        {
            // Soft focus, warm whites, minimal contrast
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying zen post-process"));
        }
        else if (AestheticStyle == TEXT("industrial"))
        {
            // Desaturated, high contrast, cool shadows
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying industrial post-process"));
        }
        else
        {
            // Default cinematic look
            UE_LOG(LogTemp, Log, TEXT("[FEL] Applying default cinematic post-process"));
        }
    }
}
