import Foundation

// NexusSceneLoader — makes the declared Nexus architecture actually true.
//
// NexusProject.json has always said:
//   "All scenes are JSON-defined NexusScene descriptors rendered by
//    NexusSceneView via SwiftUI Canvas."
// Until now that was aspirational. No Swift file referenced NexusStarter or
// any .nexus.json, the descriptors were never added to the Xcode project so
// they were never bundled, and 18 of the 20 the venue registry named did not
// exist. Scenes came from NexusScene.default(for:) — hardcoded, in code.
//
// Worse, the ONE descriptor that did exist could not be read. It was written
// by hand as:
//     {"type": "skeleton", "category": "plyometric", ...}
//     "position": { "x": 0.35, "y": 0.72 }
// while Swift's synthesized Codable for an enum-with-associated-values and
// for CGPoint expects:
//     {"skeleton": {"category": "Plyometric", "amplitude": 1}}
//     "position": [0.35, 0.72]
// Decoding it fails with `typeMismatch(Array<Any> ... found a dictionary`.
// Nothing noticed, because nothing ever tried.
//
// All 20 descriptors are now GENERATED by encoding the real types
// (tools/nexus_scenegen), so that class of drift cannot recur: if the model
// changes and the generator is not re-run, the round-trip assertion fails.
//
// DESIGN: loading NEVER throws and never returns nil. A missing or corrupt
// descriptor falls back to NexusScene.default(for:) with a diagnostic. A
// scene file is an optimisation over hardcoded defaults, not a dependency —
// shipping a build that black-screens because one JSON was left out of a
// target would be a worse failure than the one this replaces.

enum NexusSceneLoadOutcome: Equatable, Sendable {
    case bundled          // decoded from the app bundle
    case fallbackMissing  // no descriptor found
    case fallbackInvalid  // descriptor present but undecodable
}

struct NexusSceneLoadResult: Sendable {
    let scene: NexusScene
    let outcome: NexusSceneLoadOutcome
    let detail: String?
}

enum NexusSceneLoader {

    /// Subdirectory the descriptors are bundled under. `FinalEvolutionLab` is
    /// a synchronized root group, so everything in Resources/ is copied into
    /// the app automatically — no project edit needed to add a scene.
    static let resourceSubdirectory = "Resources/NexusScenes"

    /// Load a mode's scene, falling back to the in-code default.
    ///
    /// `bundle` is injectable so tests can load fixtures without the app.
    static func load(_ mode: GameModeId, prq: Double = 50, bundle: Bundle = .main) -> NexusSceneLoadResult {
        let name = mode.rawValue + ".nexus"

        guard let url = url(for: name, in: bundle) else {
            return NexusSceneLoadResult(
                scene: .default(for: mode, prq: prq),
                outcome: .fallbackMissing,
                detail: "no \(name).json in the bundle — using the in-code default")
        }

        do {
            let data = try Data(contentsOf: url)
            var scene = try JSONDecoder().decode(NexusScene.self, from: data)

            // A descriptor filed under the wrong mode is a content error the
            // type system cannot catch, and it would present as "the wrong
            // game loaded" — worth failing loudly rather than rendering it.
            guard scene.gameModeId == mode else {
                return NexusSceneLoadResult(
                    scene: .default(for: mode, prq: prq),
                    outcome: .fallbackInvalid,
                    detail: "\(name).json declares gameModeId '\(scene.gameModeId.rawValue)' "
                          + "but was loaded for '\(mode.rawValue)'")
            }

            // PRQ is a per-session, per-athlete value, so it is applied at load
            // time rather than baked into the descriptor. Descriptors stay
            // static and cacheable; the athlete's readiness stays live.
            scene.physicsConfig.applyPRQ(prq)

            return NexusSceneLoadResult(scene: scene, outcome: .bundled, detail: nil)
        } catch {
            return NexusSceneLoadResult(
                scene: .default(for: mode, prq: prq),
                outcome: .fallbackInvalid,
                detail: "\(name).json failed to decode (\(error)) — using the in-code default")
        }
    }

    /// Convenience for callers that only want a scene.
    static func scene(for mode: GameModeId, prq: Double = 50, bundle: Bundle = .main) -> NexusScene {
        load(mode, prq: prq, bundle: bundle).scene
    }

    /// Load every mode. Used by the preflight below and by tests.
    static func loadAll(prq: Double = 50, bundle: Bundle = .main) -> [GameModeId: NexusSceneLoadResult] {
        var out: [GameModeId: NexusSceneLoadResult] = [:]
        for mode in GameModeId.allCases {
            out[mode] = load(mode, prq: prq, bundle: bundle)
        }
        return out
    }

    /// Report which modes are NOT running from a descriptor.
    ///
    /// Call once at startup and log it. The failure this guards against is
    /// silent: every mode still works via the fallback, so a descriptor that
    /// never made it into the target would otherwise be invisible until
    /// someone wondered why an edit to the JSON changed nothing.
    static func preflight(bundle: Bundle = .main) -> [String] {
        loadAll(bundle: bundle)
            .filter { $0.value.outcome != .bundled }
            .map { "[NEXUS] \($0.key.rawValue): \($0.value.detail ?? "fallback")" }
            .sorted()
    }

    private static func url(for name: String, in bundle: Bundle) -> URL? {
        // Try the subdirectory first, then a flat copy — Xcode flattens
        // resource folders unless they are added as folder references, and
        // which one you get is not worth a build failure.
        bundle.url(forResource: name, withExtension: "json", subdirectory: resourceSubdirectory)
            ?? bundle.url(forResource: name, withExtension: "json")
    }
}
