#!/usr/bin/env bash
# Sovereign Bank — production go-live checklist (run from repo root on your M4 Pro).
# Does not print secrets. You run each step with live keys in your environment.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "=== Sovereign Bank — production launch ==="
echo ""
echo "1) Database (production)"
echo "    Apply migration containing RPCs + athlete_profile_link.stripe_customer_id:"
echo "      supabase/migrations/20260326120000_stripe_webhook_service_rpcs.sql"
echo "    Options:"
echo "      A) Supabase Dashboard → SQL → paste and run (production project)."
echo "      B) supabase db push --linked   (if CLI is linked to production)"
echo ""
echo "2) Edge Function secrets (live Stripe + service role)"
echo "    export STRIPE_WEBHOOK_SIGNING_SECRET=whsec_live_..."
echo "    export STRIPE_API_KEY=sk_live_..."
echo "    export SUPABASE_SERVICE_ROLE_KEY=eyJ..."
echo "    export SUPABASE_URL=https://YOUR_PROJECT.supabase.co"
echo "    ./scripts/supabase_set_production_secrets.sh"
echo "    supabase functions deploy stripe-webhook-handler --no-verify-jwt"
echo ""
echo "3) Stripe Dashboard (live mode)"
echo "    Webhook URL: \${SUPABASE_URL}/functions/v1/stripe-webhook-handler"
echo "    Event: checkout.session.completed"
echo "    Signing secret must match STRIPE_WEBHOOK_SIGNING_SECRET."
echo ""
echo "4) Live smoke (minimal charge)"
echo "    Create a \$1.00 live Price + Payment Link in Stripe (or smallest SKU)."
echo "    Sign in on https://finalevolutiongroup.com/wallet/ (same Supabase user as app)."
echo "    Checkout from /shop/ with client_reference_id (scripted) — pay with a real card."
echo "    Confirm: sovereign_market_transactions + user_balances in Supabase;"
echo "    iOS: LabViewModel wallet updates via Realtime (FELSupabaseWalletSync)."
echo ""
echo "5) Reference"
echo "    DOCS/SOVEREIGN_STRIPE_PRODUCTION.md"
echo "    ./scripts/sovereign_stripe_e2e.sh  (swap test keys for live when validating)"
echo ""
echo "Done (manual steps above)."
