#!/usr/bin/env bash
# nexus_scenes.sh — regenerate and verify every Nexus scene descriptor.
#
#     bash tools/nexus_scenes.sh            # verify only (CI default)
#     bash tools/nexus_scenes.sh --write    # regenerate, then verify
#
# The descriptors are GENERATED by encoding the real Swift types rather than
# hand-written, because hand-written is exactly how the original one ended up
# undecodable: it used {"type":"skeleton",...} and {"x":..,"y":..} where the
# synthesized Codable expects {"skeleton":{...}} and [x, y]. It parsed fine as
# JSON and failed to decode into NexusScene — and nothing noticed, because
# nothing loaded it.
#
# Generating from the types makes drift impossible to ship: change the model
# without regenerating and the verify step fails.
#
# Both steps run on Linux, so this is CI-able without a Mac.

set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

SWIFT_ROOT="${SWIFT_ROOT:-$HOME/.swift-toolchain}"
OUT="FinalEvolutionLab/Resources/NexusScenes"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
g=$'\033[32m'; r=$'\033[31m'; y=$'\033[33m'; d=$'\033[2m'; o=$'\033[0m'

SWIFTC="$(command -v swiftc || echo "$SWIFT_ROOT/usr/bin/swiftc")"
[ -x "$SWIFTC" ] || { echo "  ${y}SKIP${o} no Swift toolchain — bash tools/swift_typecheck.sh --install"; exit 0; }

# The model files import CoreGraphics (Apple module name only — Foundation
# provides CGPoint/CGFloat on Linux) and use `nonisolated` on types (Swift
# 6.1+). Both are stripped for this host build ONLY; product source untouched.
prep() {
  for f in NexusScene NexusSceneLoader GameModeId; do
    sed -e 's/^import CoreGraphics$//' -e 's/^nonisolated //' \
        "FinalEvolutionLab/Models/$f.swift" > "$WORK/$f.swift"
  done
  sed -e 's/^nonisolated //' -e 's/^    nonisolated /    /' \
      "FinalEvolutionLab/Models/Exercise.swift" > "$WORK/Exercise_full.swift" 2>/dev/null || true
  # Exercise.swift pulls in UI types; only ExerciseCategory is needed here.
  cat > "$WORK/Deps.swift" <<'EOF'
import Foundation
enum Exercise {
    enum ExerciseCategory: String, Codable, Sendable, CaseIterable {
        case plyometric = "Plyometric", strength = "Strength", mobility = "Mobility"
        case agility = "Agility", recovery = "Recovery"
    }
}
EOF
  rm -f "$WORK/Exercise_full.swift"
}

if [ "${1:-}" = "--write" ]; then
  echo; echo "  ${d}generating descriptors…${o}"
  prep
  cp tools/nexus_scenegen/SceneGen.swift "$WORK/main.swift"
  "$SWIFTC" -swift-version 5 -o "$WORK/scenegen" "$WORK"/*.swift 2>&1 | grep ': error' && exit 1
  mkdir -p "$OUT"
  "$WORK/scenegen" "$OUT" || exit 1
  rm -f "$WORK/main.swift" "$WORK/scenegen"
fi

echo; echo "  ${d}verifying with the real NexusSceneLoader…${o}"
prep
cp tools/nexus_scenegen/VerifyScenes.swift "$WORK/main.swift"
"$SWIFTC" -swift-version 5 -o "$WORK/verify" "$WORK"/*.swift 2>&1 | grep ': error' && exit 1

if "$WORK/verify" "$OUT"; then
  echo "  ${g}PASS${o}  every mode loads from its descriptor"
  exit 0
else
  echo "  ${r}FAIL${o}  see above — regenerate with: bash tools/nexus_scenes.sh --write"
  exit 1
fi
