const MODE_IMAGE_BY_CATEGORY = {
  Basketball: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800",
  Combat: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=800",
  Field: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800",
  Precision: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800",
  Court: "https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800",
  Board: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800",
  Performance: "https://images.unsplash.com/photo-1566838616631-f2618f74a6a2?w=800",
  Academy: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800",
  Party: "https://images.unsplash.com/photo-1511882150382-421056c89033?w=800",
  Shop: "https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800",
};

export const FEL_ARENA_MODES = [
  ["basketball_h2h", "Street · 1v1", "Basketball", "VeniceBeach", "1v1", "3 min", "production", "3D_UE5", "shooting"],
  ["basketball_dunk", "Dunk Contest", "Basketball", "VeniceBeach", "Solo", "5 min", "production", "3D_UE5", "timing"],
  ["basketball_dunk_3d", "Dunk Contest · NEXUS 3D", "Basketball", "VeniceBeach", "Solo", "5 min", "production", "3D_UE5", "timing"],
  ["basketball_dunk_irl", "Dunk Contest · IRL Capture", "Basketball", "Device Camera", "Solo", "5 min", "production", "IRL", "capture"],
  ["basketball_3v3", "Street · 3v3", "Basketball", "VeniceBeach", "3v3", "8 min", "production", "3D_UE5", "strategy"],
  ["karate_h2h", "Karate · 1v1", "Combat", "ZenDojo", "1v1", "3 min", "production", "3D_UE5", "combat"],
  ["karate_endless", "Karate · Endless", "Combat", "ZenDojo", "Solo", "Endless", "production", "3D_UE5", "endurance"],
  ["baseball", "Baseball · Ballpark", "Field", "BaseballPark", "Solo", "5 min", "production", "3D_UE5", "timing"],
  ["football", "Football · Kick Return", "Field", "GridironStadium", "Solo", "4 min", "production", "3D_UE5", "reflex"],
  ["soccer", "Soccer · Stadium", "Field", "Soccer_Stadium", "Solo", "3 min", "production", "3D_UE5", "shooting"],
  ["golf", "Golf · Links", "Precision", "Links_Golf_Course", "Solo", "5 min", "production", "3D_UE5", "precision"],
  ["tennis", "Tennis · Court", "Court", "Tennis_Court", "1v1", "3 min", "production", "3D_UE5", "reflex"],
  ["volleyball", "Volleyball · Sand Court", "Court", "Sand_Court", "2v2", "3 min", "production", "3D_UE5", "reflex"],
  ["surfing", "Surf · Line", "Board", "VeniceBeach", "Solo", "3 min", "production", "3D_UE5", "balance"],
  ["gymnastics", "Gymnastics · Floor", "Performance", "Training_Floor", "Solo", "4 min", "production", "3D_UE5", "timing"],
  ["brain_brawl", "Academy · Brain Brawl", "Academy", "Neuro_Arena", "Solo", "2 min", "production", "3D_UE5", "quiz"],
  ["who_scene_it", "Who Scene It", "Academy", "Neuro_Arena", "2-8", "15 min", "production", "3D_UE5", "quiz"],
  ["court_carnival", "Court Carnival · Arcade", "Party", "VeniceBeach", "2-4", "30 min", "production", "3D_UE5", "strategy"],
  ["skateboarding", "Skate · Park", "Board", "Skate_Park", "Solo", "3 min", "production", "3D_UE5", "timing"],
  ["snowboarding", "Snow · Line", "Board", "Mountain_Slope", "Solo", "3 min", "production", "3D_UE5", "reflex"],
  ["market_browse", "Sovereign Shop", "Shop", "Luma_Venice_Shop", "Browse", "Open", "non-game-module", "module", "shop"],
  ["movement_lab", "Movement Lab · Education", "Academy", "Movement_Lab", "Solo", "Tutorial", "preview", "3D_UE5", "education"],
].map(([id, displayName, category, venue, playerCount, duration, status, renderMode, gameType]) => ({
  id,
  name: displayName,
  display_name: displayName,
  category,
  venue,
  status,
  release_state: status,
  render_mode: renderMode,
  nexus_runtime_mode_id: id === "basketball_dunk_3d" ? "basketball_dunk" : id,
  player_count: playerCount,
  duration,
  difficulty: category === "Academy" ? "Cognitive" : "Adaptive",
  game_type: gameType,
  playable: status === "production" && id !== "market_browse",
  image_url: MODE_IMAGE_BY_CATEGORY[category] || MODE_IMAGE_BY_CATEGORY.Board,
  description: `${displayName} is aligned to the canonical NEXUS mode registry.`,
}));

