# fel_import_environments.py
# Auto-generated by FEL Environment Pipeline
# Run in UE5 Editor: Edit > Editor Preferences > Python > Execute

import unreal
import json
import os

def import_generated_environments():
    """Import all generated environment assets into UE5."""
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    editor_util = unreal.EditorAssetLibrary

    # Find manifest
    manifest_paths = [
        os.path.join(unreal.Paths.project_content_dir(),
                     "FEL", "Config", "environment_manifest.json"),
        os.path.join(unreal.Paths.project_dir(),
                     "GeneratedAssets", "Environments", "environment_manifest.json"),
    ]

    manifest_data = None
    for path in manifest_paths:
        if os.path.exists(path):
            with open(path, "r") as f:
                manifest_data = json.load(f)
            break

    if not manifest_data:
        unreal.log_error("[FEL] Environment manifest not found")
        return

    environments = manifest_data.get("environments", {})
    imported = 0
    skipped = 0

    for env_id, env_data in environments.items():
        if env_data.get("status") != "ready":
            skipped += 1
            continue

        dest_path = f"/Game/FEL/Environments/Generated/{env_id}"

        # Import equirectangular texture
        equirect = env_data.get("equirect_path")
        if equirect and os.path.exists(equirect):
            task = unreal.AssetImportTask()
            task.filename = equirect
            task.destination_path = dest_path
            task.destination_name = f"T_{env_id}_Equirect"
            task.automated = True
            task.save = True
            task.replace_existing = True

            # Configure texture import
            options = unreal.FbxImportUI()
            task.options = options

            asset_tools.import_asset_tasks([task])
            imported += 1
            unreal.log(f"[FEL] Imported equirect for {env_id}")

        # Import cubemap faces
        cubemap_dir = env_data.get("cubemap_dir")
        if cubemap_dir and os.path.isdir(cubemap_dir):
            for face in ["PosX", "NegX", "PosY", "NegY", "PosZ", "NegZ"]:
                face_path = os.path.join(cubemap_dir, f"{face}.png")
                if os.path.exists(face_path):
                    task = unreal.AssetImportTask()
                    task.filename = face_path
                    task.destination_path = f"{dest_path}/Cubemap"
                    task.destination_name = f"T_{env_id}_{face}"
                    task.automated = True
                    task.save = True
                    asset_tools.import_asset_tasks([task])

        # Import video texture
        video_tex = env_data.get("video_texture_path")
        if video_tex and os.path.exists(video_tex):
            # Video textures need FileMediaSource
            task = unreal.AssetImportTask()
            task.filename = video_tex
            task.destination_path = f"{dest_path}/Video"
            task.destination_name = f"V_{env_id}"
            task.automated = True
            task.save = True
            asset_tools.import_asset_tasks([task])

        # Import parallax layers
        for i, layer_path in enumerate(env_data.get("parallax_layers", [])):
            if os.path.exists(layer_path):
                layer_name = os.path.basename(layer_path).replace(".png", "")
                task = unreal.AssetImportTask()
                task.filename = layer_path
                task.destination_path = f"{dest_path}/Layers"
                task.destination_name = f"T_{env_id}_{layer_name}"
                task.automated = True
                task.save = True
                asset_tools.import_asset_tasks([task])

        # Import thumbnail
        thumb = env_data.get("thumbnail_path")
        if thumb and os.path.exists(thumb):
            task = unreal.AssetImportTask()
            task.filename = thumb
            task.destination_path = f"{dest_path}"
            task.destination_name = f"T_{env_id}_Thumb"
            task.automated = True
            task.save = True
            asset_tools.import_asset_tasks([task])

    unreal.log(f"[FEL] Environment import complete: {imported} imported, {skipped} skipped")


def create_environment_materials():
    """Create dynamic materials for each imported environment."""
    editor_util = unreal.EditorAssetLibrary
    material_factory = unreal.MaterialFactoryNew()
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

    # Create base sky sphere material
    base_mat_path = "/Game/FEL/Environments/Materials/M_FEL_DynamicSky"
    if not editor_util.does_asset_exist(base_mat_path):
        asset_tools.create_asset(
            "M_FEL_DynamicSky",
            "/Game/FEL/Environments/Materials",
            unreal.Material,
            material_factory
        )
        unreal.log("[FEL] Created base dynamic sky material")

    # Create parallax layer material
    parallax_mat_path = "/Game/FEL/Environments/Materials/M_FEL_ParallaxLayer"
    if not editor_util.does_asset_exist(parallax_mat_path):
        asset_tools.create_asset(
            "M_FEL_ParallaxLayer",
            "/Game/FEL/Environments/Materials",
            unreal.Material,
            material_factory
        )
        unreal.log("[FEL] Created parallax layer material")


def setup_post_process_presets():
    """Create post-process preset data assets for each aesthetic style."""
    styles = ["cyberpunk", "retro", "zen", "industrial", "tropical",
              "synthwave", "cinematic"]

    for style in styles:
        unreal.log(f"[FEL] Post-process preset for style: {style}")
        # In production, create UDataAsset with post-process settings


# Main execution
import_generated_environments()
create_environment_materials()
setup_post_process_presets()
unreal.log("[FEL] Environment setup complete")
