"""
Unreal Engine Editor Python Script — Import OpenArt Enhanced Environment Assets.

Auto-generated by the OpenArt Enhanced Pipeline.
Imports all OpenArt-generated textures, props, materials, atmosphere overlays,
skybox variations, and detail decals into the UE5 content browser.

Run inside UE5 Editor:
  Edit → Editor Preferences → Python → Execute:
    EditorPython/fel_import_openart_assets.py
  or via commandlet:
    UE_CMD -run=pythonscript -script=EditorPython/fel_import_openart_assets.py

Assets are imported to: /Game/FEL/Environments/OpenArt/<env_key>/<category>/
"""

import os
import json
from pathlib import Path

try:
    import unreal
    IN_EDITOR = True
except ImportError:
    IN_EDITOR = False
    print("[INFO] Not running inside UE5 Editor — generating import preview only")


# ---------------------------------------------------------------------------
# Asset discovery
# ---------------------------------------------------------------------------

# Resolve project paths
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent
ENVIRONMENTS_ROOT = PROJECT_ROOT / "GeneratedAssets" / "Environments"
MANIFEST_PATH = ENVIRONMENTS_ROOT / "openart_asset_manifest.json"
UE_BASE_PATH = "/Game/FEL/Environments/OpenArt"

# Environment list
ENVIRONMENTS = [
    "retro_tokyo_night",
    "venice_beach_sunset",
    "cyberpunk_gym",
    "classic_nba_arena",
    "underground_bunker",
    "rooftop_cityscape",
    "winter_outdoor",
    "beach_tropical",
    "warehouse_industrial",
    "neon_arcade",
    "zen_dojo",
    "stadium_night_game",
]

# Categories and their import settings
CATEGORIES = {
    "textures": {"formats": [".png", ".tga", ".exr"], "compress": True},
    "props": {"formats": [".png", ".tga"], "compress": True},
    "materials": {"formats": [".png", ".tga", ".exr"], "compress": True, "is_pbr": True},
    "atmosphere": {"formats": [".png", ".tga"], "compress": True},
    "skybox": {"formats": [".png", ".tga", ".exr", ".hdr"], "compress": False},
    "details": {"formats": [".png", ".tga"], "compress": True},
}


def discover_assets():
    """Discover all OpenArt assets on disk."""
    assets = []
    for env_key in ENVIRONMENTS:
        openart_dir = ENVIRONMENTS_ROOT / env_key / "openart"
        if not openart_dir.exists():
            continue
        for category, settings in CATEGORIES.items():
            cat_dir = openart_dir / category
            if not cat_dir.exists():
                continue
            # Handle flat files and PBR subdirectories
            for item in sorted(cat_dir.iterdir()):
                if item.is_file() and item.suffix.lower() in settings["formats"]:
                    ue_path = f"{UE_BASE_PATH}/{env_key}/{category}"
                    assets.append({
                        "source": str(item),
                        "destination": ue_path,
                        "env_key": env_key,
                        "category": category,
                        "asset_name": item.stem,
                        "is_pbr": False,
                    })
                elif item.is_dir() and settings.get("is_pbr"):
                    # PBR material directory with albedo, normal, roughness, etc.
                    for map_file in sorted(item.iterdir()):
                        if map_file.is_file() and map_file.suffix.lower() in settings["formats"]:
                            ue_path = f"{UE_BASE_PATH}/{env_key}/{category}/{item.name}"
                            assets.append({
                                "source": str(map_file),
                                "destination": ue_path,
                                "env_key": env_key,
                                "category": category,
                                "asset_name": f"{item.name}_{map_file.stem}",
                                "is_pbr": True,
                                "map_type": map_file.stem,
                                "material_name": item.name,
                            })
    return assets


# ---------------------------------------------------------------------------
# UE5 Import
# ---------------------------------------------------------------------------

def create_import_tasks(assets):
    """Create UE5 AssetImportTask objects for all discovered assets."""
    if not IN_EDITOR:
        return []

    tasks = []
    for asset in assets:
        task = unreal.AssetImportTask()
        task.filename = asset["source"]
        task.destination_path = asset["destination"]
        task.destination_name = asset["asset_name"]
        task.replace_existing = True
        task.automated = True
        task.save = True

        # Configure texture import options
        options = unreal.FbxImportUI()
        task.options = options

        tasks.append(task)
    return tasks


def create_material_instances(assets):
    """Create UE5 Material Instances for PBR material sets."""
    if not IN_EDITOR:
        return []

    material_sets = {}
    for asset in assets:
        if asset.get("is_pbr") and asset.get("material_name"):
            key = f"{asset['env_key']}/{asset['material_name']}"
            if key not in material_sets:
                material_sets[key] = {
                    "env_key": asset["env_key"],
                    "name": asset["material_name"],
                    "maps": {},
                }
            material_sets[key]["maps"][asset["map_type"]] = asset["destination"] + "/" + asset["asset_name"]

    created = []
    for key, mat_set in material_sets.items():
        try:
            mat_path = f"{UE_BASE_PATH}/{mat_set['env_key']}/materials"
            mi_name = f"MI_{mat_set['name']}"

            # Create a Material Instance Dynamic referencing the PBR textures
            # This requires a base material M_OpenArt_PBR to exist
            base_material_path = "/Game/FEL/Materials/M_OpenArt_PBR"

            if unreal.EditorAssetLibrary.does_asset_exist(base_material_path):
                base_mat = unreal.EditorAssetLibrary.load_asset(base_material_path)
                asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

                mi = asset_tools.create_asset(
                    mi_name,
                    mat_path,
                    unreal.MaterialInstanceConstant,
                    unreal.MaterialInstanceConstantFactoryNew()
                )
                if mi:
                    mi.set_editor_property("parent", base_mat)
                    # Set texture parameters
                    for map_type, tex_path in mat_set["maps"].items():
                        param_name = f"T_{map_type.capitalize()}"
                        tex = unreal.EditorAssetLibrary.load_asset(tex_path)
                        if tex:
                            unreal.MaterialEditingLibrary.set_material_instance_texture_parameter_value(
                                mi, param_name, tex
                            )
                    unreal.EditorAssetLibrary.save_asset(f"{mat_path}/{mi_name}")
                    created.append(f"{mat_path}/{mi_name}")
        except Exception as e:
            print(f"[WARN] Could not create material instance for {key}: {e}")

    return created


def setup_texture_streaming(assets):
    """Configure texture streaming for imported assets."""
    if not IN_EDITOR:
        return

    for asset in assets:
        if asset["category"] in ("textures", "materials", "skybox"):
            tex_path = f"{asset['destination']}/{asset['asset_name']}"
            try:
                tex = unreal.EditorAssetLibrary.load_asset(tex_path)
                if tex and isinstance(tex, unreal.Texture2D):
                    # Enable streaming
                    tex.set_editor_property("never_stream", False)
                    # Set LOD group based on category
                    if asset["category"] == "skybox":
                        tex.set_editor_property("lod_group", unreal.TextureGroup.TEXTUREGROUP_SKYBOX)
                    elif asset["category"] == "textures":
                        tex.set_editor_property("lod_group", unreal.TextureGroup.TEXTUREGROUP_WORLD)
                    unreal.EditorAssetLibrary.save_asset(tex_path)
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Main execution
# ---------------------------------------------------------------------------

def main():
    print("=" * 60)
    print("  OpenArt Enhanced Assets — UE5 Import")
    print("=" * 60)

    # Discover assets
    assets = discover_assets()
    print(f"\n  Discovered {len(assets)} assets across {len(ENVIRONMENTS)} environments")

    # Categorize
    by_category = {}
    by_env = {}
    for a in assets:
        by_category[a["category"]] = by_category.get(a["category"], 0) + 1
        by_env[a["env_key"]] = by_env.get(a["env_key"], 0) + 1

    print("\n  By category:")
    for cat, count in sorted(by_category.items()):
        print(f"    {cat}: {count}")

    print("\n  By environment:")
    for env, count in sorted(by_env.items()):
        print(f"    {env}: {count}")

    if IN_EDITOR:
        # Create and run import tasks
        print("\n  Creating import tasks...")
        tasks = create_import_tasks(assets)
        if tasks:
            asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
            asset_tools.import_asset_tasks(tasks)
            print(f"  ✓ Imported {len(tasks)} assets")

        # Create material instances
        print("\n  Creating material instances...")
        materials = create_material_instances(assets)
        print(f"  ✓ Created {len(materials)} material instances")

        # Configure texture streaming
        print("\n  Configuring texture streaming...")
        setup_texture_streaming(assets)
        print("  ✓ Texture streaming configured")
    else:
        print("\n  [DRY-RUN] Import tasks that would be created:")
        for a in assets[:10]:
            print(f"    {a['source']} → {a['destination']}/{a['asset_name']}")
        if len(assets) > 10:
            print(f"    ... and {len(assets) - 10} more")

    # Generate import report
    report = {
        "total_assets": len(assets),
        "by_category": by_category,
        "by_environment": by_env,
        "environments": ENVIRONMENTS,
        "ue_base_path": UE_BASE_PATH,
        "manifest_path": str(MANIFEST_PATH),
    }
    report_path = SCRIPT_DIR / "openart_import_report.json"
    report_path.write_text(json.dumps(report, indent=2))
    print(f"\n  Report: {report_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()

# Auto-execute when loaded in UE5 Editor
main()
